jsk_tilt_laser/launch/multisense.launch

- Add use_robot_description arg to multisense.launch to prevent robot_description from conflicting with one of real robot
- Removed robot_description private param in ros_driver, which is seemed to be unused in multisense_ros

[jsk_tilt_laser] Add use_robot_description argument to multsense.launch

---

3rdparty/nlopt/Makefile

fix for https://github.com/jsk-ros-pkg/jsk_common/issues/666

[nlopt] Add LIBS='-stdc++' to avoid link error on saucy

---

jsk_network_tools/scripts/silverhammer_lowspeed_check_size.py

```
$ ./silverhammer_lowspeed_check_size.py jsk_network_tools/OCS2FC
jsk_network_tools/OCS2FC
binary format:  !BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB??
size:                34 bytes
272 bits
size w/ UDP header:  70 bytes
560 bits
$ ./silverhammer_lowspeed_check_size.py jsk_network_tools/FC2OCS
jsk_network_tools/FC2OCS
binary format:  !BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB?
size:                57 bytes
456 bits
size w/ UDP header:  93 bytes
744 bits
```

[jsk_network_tools] Add script to check size in lowspeed network

---

jsk_tilt_laser/launch/multisense.launch

We use ~high_fidelity=true in order to avoid
laser_geometry's bug to produce large sphere pointcloud
* sphere bug when we use ~high_fidelity=false

[jsk_tilt_laser] Add scan_to_cloud_chain to multisense.launch to get one-scan pointcloud.

---

3rdparty/downward/Makefile

Is there a reason that "downward" always compiles 32-bit binaries, even on 64-bit processors? This is a problem for ARM processors, becuase the `-m32` flag isn't valid, and so the compilation fails [1].
If there is no particular reason for 32-bit binaries on 64-bit processors, `DOWNWARD_BITWIDTH=native` should be used to allow the system to decide the appropriate bitwidth.
Once the new behavior is verified, the dependency on `g++-multilib` can be removed.
[1] https://csc.mcs.sdsmt.edu/jenkins/job/ros-indigo-downward_binaryrpm_21_armhfp/10/consoleFull

downward: Use native bitwidth when compiling

---

jsk_network_tools/CMakeLists.txt
jsk_network_tools/euslisp/angle-vector-compress.l
jsk_network_tools/euslisp/joint-state-compressor.l
jsk_network_tools/euslisp/joint-state-decompressor.l
jsk_network_tools/launch/joint_state_compress_sample.launch
jsk_network_tools/msg/CompressedAngleVectorPR2.msg

Originally implemented in jsk_pr2_startup by Y.Furuta [https://github.com/jsk-ros-pkg/jsk_robot/pull/243]
Update the code to
* support robots not only pr2
* support linear-joint
* add simple executable to compress/decompress `sensor_msgs/JointStates`
I'm still wondering jsk_network_tools is the best package to locate it.

[jsk_network_tools] Add euslisp script to compress/decompres joint states

---

3rdparty/nlopt/CMakeLists.txt

When I attempted to use the nlopt hydro package, the nlopt library was not being linked by packages that depended on it. I believe this is because catkin_package did not indicate that the library was being exported.
Thus I added nlopt_cxx library to catkin_package so that the library will be included by packages that depend on nlopt.

NLopt CMakeLists.txt

---

3rdparty/nlopt/CMakeLists.txt

Fix for https://github.com/jsk-ros-pkg/jsk_control/issues/211
* compile libraries under source directory and after that copy to devel space.
* Use add_custom_command instead of execute_process

[nlopt] Fix nlopt compilation to export nlopt_cxx correctly.

---

jsk_tilt_laser/launch/multisense.launch

Add sensor_tf_prefix and not_use_sensor_tf_prefix for the
robots which has '/left/image_rect_color' sensor frame instead of
'/multisense/left/image_rect_clor'

[jsk_tilt_laser] Add sensor_tf_prefix and not_use_sensor_tf_prefix to multisense.launch

---

jsk.rosbuild

1. Use ros-wrapper of hrpsys and openrtm instead of non-catkin hrpsys and openrtm. 
Because the packages are not yet ready to use it.
Need to solve [this issue](https://github.com/start-jsk/rtmros_common/issues/651)
2. Run rosdep install after call `jsk_roseus/setup.sh` not to install euslisp, jskeus and geneus.

[jsk.rosbuild] Use ros wrapper of hrpsys and openrtm and checkout euslisp, jskeus and geneus before run "rosdep install"

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/include/jsk_topic_tools/relay_nodelet.h
jsk_topic_tools/src/relay_nodelet.cpp
jsk_topic_tools/srv/ChangeTopic.srv

Add `~change_output_topic` service to jsk_topic_tools::Relay nodelet to change output topic on the fly.
It means that this relay node can behave like "inverse of mux" node.

[jsk_topic_tools] Add service interface to change output topic of relay node

---

jsk_ros_patch/image_view2/image_view2.cpp
jsk_ros_patch/image_view2/msg/ImageMarker2.msg

* add left_up_origin flag to ImageMarker2 to set the origin of text to left upper corner
* support filled flag in draw text type

[image_view2] Add left_up_origin flag to ImageMarker2 to draw text from left upper origin

---

jsk_ros_patch/collada_urdf_jsk_patch/package.xml

because it should be resolved via collada_urdf package.

[collada_urdf_jsk_patch] Remove urdf and urdfdom from package.xml

---

jsk_network_tools/scripts/silverhammer_highspeed_streamer.py
jsk_network_tools/scripts/silverhammer_lowspeed_receiver.py
jsk_network_tools/scripts/silverhammer_lowspeed_streamer.py

It' important to check system works or not

[jsk_network_tools] Publish the last time to send/receive messages

---

3rdparty/nlopt/CMakeLists.txt

* Compile under temporary directory and copy output files into devel space

[nlopt] Fix nlopt compilation and instlation

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/include/jsk_topic_tools/passthrough_nodelet.h
jsk_topic_tools/jsk_topic_tools_nodelet.xml
jsk_topic_tools/src/passthrough_nodelet.cpp
jsk_topic_tools/srv/PassthroughDuration.srv

Passthrough is a nodelet to relay topics only for specified duratoin.
For example, you can relay input poointcloud for 10 seconds to get one recognition result by this node.

[jsk_topic_tools] Add Passthrough nodelet to relay topics during specified duration

---

jsk.rosbuild

in order to ignore packages which is in local workspace correctly

[jsk.rosbuild] Run rosdep for ros/hydro and ros/hydo_parent at once

---

jsk.rosinstall

These two PRs are super important. We will use garaemon/perception_pcl instead of apt
packages until these PRs are merged.
* https://github.com/ros-perception/perception_pcl/pull/80
* https://github.com/ros-perception/perception_pcl/pull/85

[jsk.rosbuild] Use garaemon/perception_pcl instead of apt packages because it have several serious bugs

---

3rdparty/downward/CMakeLists.txt
3rdparty/downward/package.xml

First commit adds a `build_depend` on `g++-static` for `downward`. It seems that upstream `downward` forces all non-osx builds to use static linking. These libraries are provided automatically in Ubuntu, but reside in separate packages for Fedora.
rosdep key for `g++-static`: https://github.com/ros/rosdistro/blob/942f1592dbf0d208fc3d48c5cb2d70d3acb0050a/rosdep/base.yaml#L678-L680
Second commit invokes recursive call to `make` properly. See https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html#MAKE-Variable for details.
Example build failure: http://csc.mcs.sdsmt.edu/jenkins/job/ros-indigo-downward_binaryrpm_heisenbug_x86_64/25/consoleFull
Thanks,
--scott

Downward static

---

jsk.rosbuild
jsk.rosinstall
jsk.rosinstall.hydro

and use garaemon/pcl_conversions and garaemon/pcl_ros only for hydro users
* Add jsk.rosinstall.hydro for hydro
* Add garaemon/pcl_conversions and garaemon/perception_pcl to jsk.rosinstall.hydro
Because these repositories do not merge critical pull-request yet.

[jsk.rosbuild] Add garaemon/pcl_conversions to resolve fatal bug 

---

jsk_tools/src/git_commit_alias.py

You can add commit aliases liks `commit-ueda` and `commit-murooka` of jsk-ros-pkg developers, it's useful to develop software on one-machine/one-user.
Usage:
```
rosrun jsk_tools git_commit_alias.py
```

[jsk_tool] Add script to add git commit aliases like commit-ueda

---

jsk_tools/README.md
jsk_tools/env-hooks/99.jsk_tools.bash
jsk_tools/env-hooks/99.jsk_tools.zsh

Usage
-----
```
user@host $ rossetdefault pr1040
set ROS_MASTER_URI to http://pr1040:11311
[http://pr1040:11311] user@host $
user@host $ rosdefault
set ROS_MASTER_URI to http://pr1040:11311
[http://pr1040:11311] user@host $
user@host $ rossetdefault local
user@host $ rosdefault
set ROS_MASTER_URI to http://localhost:11311
```
It is recommended to write `rosdefault` in your .bashrc or .zshrc.

[jsk_tools] Add rossetdefault, rosdefault to zshrc.ros

---

jsk_tools/CHANGELOG.rst
jsk_tools/bin/force_to_rename_changelog_user.py

- [force_to_rename_changelog_user.py] add manabu -> Manabu Saito

[force_to_rename_changelog_user.py] keep order of Contributors

---

jsk_network_tools/README.md
jsk_network_tools/scripts/silverhammer_highspeed_receiver.py
jsk_network_tools/scripts/silverhammer_highspeed_streamer.py

[jsk_network_tools] Use 1500*8 bits as default packet_size for MTU:=1500
environment in silverhammer_highspeed communication

[jsk_network_tools] Use 1500*8 bits as default packet_size

---

jsk_network_tools/scripts/expand_udp_receive_buffer.sh

@garaemon Thank you for advise. I mistook value, very sorry.
also added shell option to check if this command executed successfly.

[jsk_network_tools] bugfix: fix rmem_max value; set bash option to check command executed successfly

---

jsk_tools/src/jsk_tools/sanity_lib.py

```
checkSilverHammerSubscribe("/ocs_from_fc_low_speed/output", 1 , 0.5)
```

add check SilverHammer's published topic hz check

---

jsk_network_tools/launch/simple_silverhammer_sample.launch
jsk_network_tools/scripts/silverhammer_lowspeed_streamer.py

we can change `send_rate` by reloading param:
```
rosparam set /silverhammer/ocs_streamer/send_rate 10.0
rosservice call /silverhammer/set_send_rate
```

[jsk_network_tools] add set send_rate service for lowspeed streamer

---

jsk.rosinstall.hydro

pcl_conversions because mportant PR to pcl_ros is merged

[jsk.rosinstall.hydro] Use ros-preception branch for pcl_ros and

---

jsk_tools/launch/record_axis_camera.launch
jsk_tools/package.xml

```sh
$ roslaunch jsk_tools record_axis_camera.launch
... logging to /home/wkentaro/.ros/log/9569da06-14b6-11e5-80a8-7831c1bb6b6c/roslaunch-cobra-9917.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
Axis password?:
```
or
```sh
$ roslaunch jsk_tools record_axis_camera.launch ask_password:=false password:=XXXX
```
default output file should be saved as `~/.ros/output.avi' (without no customization)

[jsk_tools] Add launch to record axis camera

---

jsk.rosbuild

in existing function `runsudo` used `sudo sh -c "$*"`, which collapse some code that includes redirects.
for example:
```
runsudo sh -c "echo \"deb $DEBIAN_REPOSITORY `lsb_release -cs` main\" > /etc/apt/sources.list.d/ros-latest.list"
```
this is expanded to:
```
sudo sh -c 'sh -c echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
```
as above, expanding codes using `"$*"` removes top-level `"`, which causes unexpected behavior.

[jsk.rosbuild] fix no sudo option in jsk.rosbuild

---

jsk.rosinstall

pr2_gripper_sensor_action
this is to avoid error in jsk_pr2_startup/pr2.launch because of missing launch file.
it is solved only in ros-shadow-fixed.

[jsk.rosinstall] jsk_pr2_startup/pr2.launch requires launch file in

---

jsk_tools/src/jsk_tools/__init__.py
jsk_tools/src/jsk_tools/sanity_lib.py

I don't think this breaks conventional interfaces.

[jsk_tools] Check msg type is same as published one

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/launch/standalone_complexed_nodelet_sample.launch
jsk_topic_tools/src/standalone_complexed_nodelet.cpp

It reads nodelet clients from rosparam and launch them. It is a general
model for nodelet like stereo_image_proc. It does not need different
processes for manager/clients.
sample: standalone_complexed_nodelet_sample.launch
Format of the rosparameter is:
```yaml
nodelets:
- name: relay_0
type: jsk_topic_tools/Relay
remappings:
- from: ~input
to: input
- name: relay_1
type: jsk_topic_tools/Relay
remappings:
- from: ~input
to: relay_0/output
- name: relay_2
type: jsk_topic_tools/Relay
remappings:
- from: ~input
to: relay_1/output
```

[jsk_topic_tools] Introduce new nodelet manager called standalone_complexed_nodelet.

---

jsk_network_tools/CMakeLists.txt
jsk_network_tools/launch/simple_silverhammer_internal_buffer_openni_sample.launch
jsk_network_tools/msg/SilverhammerInternalBuffer.msg
jsk_network_tools/scripts/silverhammer_highspeed_receiver_with_internal_buffer.py
jsk_network_tools/src/silverhammer_highspeed_internal_receiver.cpp

Only core is implemented in c++.
It cooperates with python thin wrapper and bridged via ros between them.
* python is too slow to implement receiver in one process
* Giant lock does not allow us to write parallel processes
* python multiprocessing may generate zombie process
* Because python signal/exception mechanism is not robust with multiprocessing and socket programming
* Implement UDP server in C++ to write `receiving packets` and `collecting packets` in different thread for performance reason.
* But C++ is not good at Meta Object Protocol, so C++ UDP server just sends not-deserialized ROS buffer to python wrapper via normal ROS topic protocol and convert it into serialized ROS message in python, because we'd like to specify different classes from ros parameters.

[jsk_network_tools] Add C++ implementation of silverhammer_highspeed_receiver.

---

jsk_tools/env-hooks/99.jsk_tools.sh

**BEFORE**
```
set ROS_MASTER_URI to http://pr1012.jsk.imi.i.u-tokyo.ac.jp:11311
172.17.42.1
set ROS_IP and ROS_HOSTNAME to 10.68.0.100
```
**AFTER**
```
set ROS_MASTER_URI to http://pr1012.jsk.imi.i.u-tokyo.ac.jp:11311
set ROS_IP and ROS_HOSTNAME to 10.68.0.100
```

Remove no need stdout in rossetip

---

jsk_data/Makefile

https://github.com/jsk-ros-pkg/jsk_common/issues/1108
Show size of bag files as well as their names.
```
$ make small-list
total 9.1G
2.6G 2014_10_15_fridge_demo.bag
935M amt_hrp2_lie_on_stomach_2011-07-19-10-17-25.bag
26M dinosauor.pcd
467M hrp2016-rotate-elephant-onehand-20101021.bag
432M hrp2-hand-over-object-20100610.bag
310M hrp2-raw-camera-images-for-cr-capture.bag
22M hrp2-sample-20100619.bag
1.8M hrp2w-room602-mapping-20100415-2.bag
97M hrp4r-walk-hat-exp-without-passer-by-2012-02-15-20-42-10.bag
220M hrp4r-walk-hat-exp-without-passer-by-2012-02-15-21-08-01.bag
182M hrp4r-walk-hat-exp-with-passer-by-2012-02-15-21-22-45.bag
228M hrp4r-walk-hat-exp-with-passer-by-2012-02-15-21-34-09.bag
28M kago1.pcd
38M kago2.pcd
1.1G kenzo-armarker-20111216.bag
1.4G kojiro-view-20111218.bag
15M …
```

[jsk_data] Show size of files when listing remote bag files

---

jsk.rosinstall

This helps to find out version divergence.
```
% wstool info jsk-ros-pkg/*
workspace: /home/wkentaro/ros/indigo/src
Localname                     S SCM  Version-Spec UID  (Spec)                 URI  (Spec) [http(s)://...]
---------                     - ---- ------------ -----------                 ---------------------------
jsk-ros-pkg/jsk_openni_kinect M git  master       eb6866982139                github.com/jsk-ros-pkg/jsk_openni_kinect.git
jsk-ros-pkg/jsk_3rdparty        git  master       3d3ed2e4200a                github.com/jsk-ros-pkg/jsk_3rdparty.git
jsk-ros-pkg/jsk_common_msgs     git  master       d10f85577809                github.com/jsk-ros-pkg/jsk_common_msgs.git
jsk-ros-pkg/jsk_common        V git  master       817329cbf7b4 (3c20fefa1200) …
```

Specify version: master in rosinstall for jsk-ros-pkg/*

---

jsk_tools/README.md
jsk_tools/env-hooks/99.jsk_tools.sh
jsk_tools/package.xml

```
$ restart_travis jsk-ros-pkg/jsk_common 1258.2
```

[jsk_tools] Add restart_travis function to do it from command line

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/package.xml

fix for https://github.com/jsk-ros-pkg/jsk_common/issues/1123

[jsk_topic_tools] Depends on roscpp and rostime explicitly

---

jsk_topic_tools/launch/topic_buffer_client_sample.launch
jsk_topic_tools/launch/topic_buffer_server_sample.launch
jsk_topic_tools/test/test_hz_measure.py
jsk_topic_tools/test/test_topic_buffer.test
jsk_topic_tools/test/test_topic_buffer_close_wait.test
jsk_topic_tools/test/test_topic_buffer_fixed_rate.test
jsk_topic_tools/test/test_topic_buffer_fixed_rate_and_update_rate.test
jsk_topic_tools/test/test_topic_buffer_update_rate.test

It's difficult to say whether this change is good or not, but these tests are now stable and we can ignore debug-helpful messages

[jsk_topic_tools] Supress output messages from testing

---

README.md

scudcloud is a desktop client of slack.
You can use it on 14.04 without no effort but on 12.04 we need ppas.

Add document how to install scudcloud on 12.04

---

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h
jsk_topic_tools/src/connection_based_nodelet.cpp

For #1132 
```
% rosrun jsk_topic_tools string_relay
[ INFO] [1443503176.478853037]: Initializing nodelet with 8 worker threads.
[ INFO] [1443503176.521582239]: ack1
[ INFO] [1443503176.521756137]: ack2
```
it won't enter the wallTimerCallback method, do you have any idea about this?
(no ack3 and ack4)

[jsk_topic_tools] Warning for no connection in ConnectionBasedNodelet

---

jsk_data/src/jsk_data/cli.py

Because gdrive does not return full title if it is longer than 40
Closes #1155

[jsk_data] Estimate filename if longer than 40

---

jsk_network_tools/CMakeLists.txt

```
/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_common/src/jsk_common/jsk_network_tools --package=jsk_network_tools --results-filename test_test_all_type_low_speed.xml --results-base-dir /workspace/ros/ws_jsk_common/build/jsk_network_tools/test_results /workspace/ros/ws_jsk_common/src/jsk_common/jsk_network_tools/test/test_all_type_low_speed.test 
... logging to /workspace/jsk-ros-pkg/jsk_common/log/rostest-e92918266336-8154.log
[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_common/build/jsk_network_tools/test_results/jsk_network_tools/rostest-test_test_all_type_low_speed.xml
testtest_all_type_low_speed ... FAILURE!
FAILURE: Package [jsk_network_tools] for test node [jsk_network_tools/test_all_type_low_speed.py] does not exist
File …
```

[jsk_network_tools] Disable test

---

jsk_tools/package.xml
jsk_tools/src/delay_timestamp.py

For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1288

[jsk_tools] Add delay_timestamp.py

---

jsk_topic_tools/scripts/topic_statistics.py

utility script for measurement of data sizes
usage:
```
./topic_statistics.py                          ⮂  
Usage: topic_statistics.py [options] topic_name
Options:
-h, --help      show this help message and exit
-w WINDOW_SIZE  
-d DURATION
```
e.g.
```
$ ./topic_statistics.py -w 50 wide_stereo/left/image_rect
start subscribing wide_stereo/left/image_rect
waiting for 50 msgs...
received 51 messages for 2.027576924 [sec]
size amount:	15670.617 [kB]
size avg:	307.267 [kB/msg]
```
```
$ ./topic_statistics.py -d 10 wide_stereo/left/image_rect
start subscribing wide_stereo/left/image_rect
waiting for 10 [sec]...
received 280 messages for 10.014266968 [sec]
size amount:	86034.76 [kB]
size avg:	307.267 [kB/msg]
rate:		8591.21893544 [kB/sec]
```

[jsk_topic_tools] add topic_statistics.py

---

jsk_tools/src/test_stdout.py

This should be reasonable because rosparam also strip parameter
automatically.

[jsk_tools] Remove test stdout space

---

jsk_topic_tools/CMakeLists.txt

Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/1330

Use gcc -z defs to check undefined symbols in shared objects

---

jsk_tools/bin/kill_after_seconds.py

for example, this script benchmark effect of the number of particle:
```sh
#!/bin/sh
set -e
echo "particle,time,ang_err,dis_err" > result_particle_num.csv
for d in $(seq 10 100 5000)
do
rosparam set /particle_filter_tracker/max_particle_num $d
python kill_after_seconds.py 30 roslaunch tracking.launch voxel_grid_leaf_size:=0.02 octree_resolution:=0.01 &
rostopic echo /particle_filter_tracker/output/latest_time -n 1
sleep 5
echo -n "$d," >> result_particle_num.csv
time=$(rostopic echo /particle_filter_tracker/output/average_time/data -n 1 | head -n 1)
ang=$(rostopic echo /particle_filter_tracker/output/rms_angle_error/data -n 1 | head -n 1)
dis=$(rostopic echo /particle_filter_tracker/output/rms_distance_error/data -n 1 | head -n 1)
echo "$time,$ang,$dis" >> result_particle_num.csv
for job …
```

[jsk_tools] Add kill_after_seconds.py. It will kill a process after specified seconds. It is useful to handle roslaunch for benchmarking.

---

jsk_tools/CMakeLists.txt
jsk_tools/bin/git-jsk-commit
jsk_tools/env-hooks/99.jsk_tools.sh

Usage:
```
git jsk-commit -a
```
Modified:
jsk_tools/CMakeLists.txt
jsk_tools/env-hooks/99.jsk_tools.sh

[jsk_tools] git-jsk-commit as git's subcommand

---

jsk_tools/bin/git-jsk-commit
jsk_tools/src/git_commit_alias.py

* Use "$@" in jsk-commit to keep quotes across shell script.
* Use jsk-commit command for commit-ueda, commit-mmurooka and so on
Modified:
jsk_tools/bin/git-jsk-commit
jsk_tools/src/git_commit_alias.py

[jsk_tools] Use jsk-commit for git alias like 'commit-ueda'.

---

jsk_tools/src/jsk_tools/bag_plotter.py

Makefile to convert bag file to plot image (for jaxon) .
```makefile
bag_files = $(shell find . -name '*.bag')
image_files = $(subst .bag,.pdf,${bag_files})
plotter_py = $(shell rospack find jsk_tools)/src/jsk_tools/bag_plotter.py
config_file = $(shell rospack find jaxon_ros_bridge)/config/plotter_configs/plotter.yaml
all: ${image_files}
.SUFFIX: .bag .pdf
%.pdf: %.bag ${plotter_py} ${config_file}
rosrun jsk_tools bag_plotter.py ${config_file} $< -o $@
```

[jsk_tools/bag_plotter] Add -o to save figure automatically

---

jsk_topic_tools/cmake/single_nodelet_exec.cpp.in

Modified:
- jsk_topic_tools/cmake/single_nodelet_exec.cpp.in

[jsk_topic_tools] Return to avoid segfault when --inout opt

---

jsk_coordination_system/dynamic_tf_publisher/src/tf_publish.py

indigoからはqueue_sizeを指定しないと以下のように警告が出るようです．
queue_sizeはhydroから実装されているようです．
```bash
/home/player/ros/indigo/src/jsk-ros-pkg/jsk_common/jsk_coordination_system/dynamic_tf_publisher/src/tf_publish.py:34: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
self.pub_tf = rospy.Publisher("/tf", tf.msg.tfMessage)
```
- http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers

queue_size is new in hydro and necessary from indigo

---

jsk_tools/bin/battery_capacity_summary.py

[jsk_tools/bin/battery_capacity_summary.py] print N/A for unavailable data

---

jsk_data/src/jsk_data/cli.py

This is necessary to fix not found error for `pubinfo` command

[jsk_data] Omitted name of filename for gdrive go cli

---

doc/jsk_tools/cltools/config_switch.rst
jsk_tools/CMakeLists.txt
jsk_tools/env-hooks/99.config_switch.bash
jsk_tools/env-hooks/99.config_switch.zsh

Modified:
- jsk_tools/CMakeLists.txt
Added:
- jsk_tools/env-hooks/99.dotfile.bash
- jsk_tools/env-hooks/99.dotfile.zsh
```
$ config_switch wkentaro /bin/bash
Switching user: wkentaro -> wkentaro
Linked .bashrc -> .bashrc.wkentaro
Linked .zshrc -> .zshrc.wkentaro
Linked .vimrc -> .vimrc.wkentaro
Linked .vim -> .vim.wkentaro
Linked .gitconfig -> .gitconfig.wkentaro
Logging in as 'wkentaro' with '/bin/bash'
$ cat ~/.ros/jsk_tools/current_config
wkentaro
/bin/bash
$ config_switch
Current user: wkentaro
Current shell: /bin/bash
```

[jsk_tools] Handle shell and dotfiles for shared computers

---

jsk_tools/cmake/shell_test.cmake.em

Modified:
- jsk_tools/cmake/shell_test.cmake.em

[jsk_tools] Replace slash to create a valid test name

---

jsk_tools/src/jsk_tools/sanity_lib.py
jsk_tools/src/test_topic_published.py

- jsk_tools/src/test_topic_published.py: set default timeout to 10 sec
- jsk_tools/src/sanity_lib.py: add timouetout informatoin

- jsk_tools/src/test_topic_published.py: set default timeout to 10 sec

---

jsk_tools/CMakeLists.txt

Because using python -c 'import sys; sys.exit(ord('$ENV{ROS_DISTRO}') >= ord('indigo'))' is redundant and sometimes fails unexpectedly.

[jsk_tools] Stable ros version check by STRGREATER

---

doc/jsk_topic_tools/scripts/is_synchronized.rst
jsk_topic_tools/scripts/is_synchronized

```
% ./is_synchronized /raw_image_rgb/image_color /depth_image_32fc1/image_depth -a
****************** Test Condition ******************
sync_policy: Approximate
topics:
- /raw_image_rgb/image_color [sensor_msgs/Image]
- /depth_image_32fc1/image_depth [sensor_msgs/Image]
timeout: 5 seconds
queue_size: 100
slop: 0.1
****************************************************
listening these topics for at most 5 seconds in rostime
synchronized in 1.0 seconds
these topics are: 'synchronized'
```

[jsk_topic_tools] Support async in is_synchronized

---

jsk_tools/src/test_topic_published.py

When ``/use_sim_time`` is true, the time is temporary set to 0.000000 at initiation of a program.
This causes `TopicPublishedChecker` to crash. A launch file that crashes with this program is below.
The rosbag in the launch file can be downloaded from here.
https://drive.google.com/file/d/0BzBTxmVQJTrGRERod3E5S3RxdE0/view?usp=sharing
```
<launch>
<param name="/use_sim_time" value="true" type="bool"/> 
<node name="rosbag_play"
pkg="rosbag" type="play"
args="$(find jsk_2016_01_baxter_apc)/test_data/sib_kinect2.bag --loop --clock">
</node>
<test test-name="sib_test"
name="sib_test"
pkg="jsk_tools" type="test_topic_published.py">
<rosparam>
topic_0: /kinect2_torso/hd/camera_info
timeout_0: 10
</rosparam>
</test>
</launch>
```

[jsk_topic_tools] test_topic_published.py waits when rosbag is used

---

jsk_topic_tools/src/jsk_topic_tools/log_utils.py
jsk_topic_tools/test/test_python_log_utils.py
jsk_topic_tools/test/test_python_log_utils.test

In roscpp, there is ROS_XXX_THROTTLE to write log periodically.
http://wiki.ros.org/rospy/Overview/Logging
```
ROS_DEBUG_THROTTLE(60, "This message will print every 60 seconds");
```
In rospy, there is **no** logXXX_throttle like logwarn_throttle.
http://wiki.ros.org/rospy/Overview/Logging

Implement logXXX_throttle for Python to write log periodically

---

jsk_tools/package.xml
jsk_tools/src/jsk_tools/sanity_lib.py
jsk_tools/test/python/test_sanity_lib.py

Remove dependency on python-termcolor

---

jsk_data/launch/pr2_play.launch

Close https://github.com/jsk-ros-pkg/jsk_common/issues/1429

[jsk_data] Remap /kinect_head topics to /kinect_head_c2 to play rosbag for pr2

---

jsk_data/launch/hrp2_play.launch

HRP2 model with HRP3 hand is used as default.
By setting `use_collada_model:=true`, you can use model in previous version, (but I think no one wants to use model without hand.)

[jsk_data] use urdf model with hand for robot_description when playing with hrp2

---

jsk_network_tools/CMakeLists.txt
jsk_network_tools/launch/wifi_status.launch
jsk_network_tools/msg/WifiStatus.msg
jsk_network_tools/scripts/wifi_status.py

add state publisher for wifi
```bash
---
header: 
seq: 83
stamp: 
secs: 1472296685
nsecs: 763282060
frame_id: ''
interface: wlan0
enabled: True
connected: True
ssid: <ssid>
frequency: 5.18 GHz
access_point: <mac address>
bitrate: 86.7 Mb/s
tx_power: 22 dBm
link_quality: 0.428571428571
signal_level: -80 dBm
```

[jsk_network_tools] add wifi_status.py

---

jsk_tools/env-hooks/99.jsk_tools.sh
jsk_tools/package.xml

for future compatibility and multi platform.

[jsk_tools/env-hooks/99.jsk_tools.sh] use ip for rossetip instead of ifconfig

---

jsk_data/CMakeLists.txt
jsk_data/launch/baxter_record.launch
jsk_data/launch/common_record.launch
jsk_data/launch/hrp2_record.launch
jsk_data/launch/pr2_record.launch
jsk_data/launch/template_pr2_record.launch
jsk_data/launch/urata_record.launch
jsk_data/package.xml

- add `bagfile_prefix` argument for `XXX_record.launch`
destination bag file is `$(arg save_dir)/$(arg bagfile_prefix)_YYYY-mm-dd-HH-MM-SS.bag`
Without this PR, we can set only directory and prefix is always empty.
```bash
/removable/bagfile/furushchev/elevator_20160106$ ls
_2016-01-05-23-50-54.bag  _2016-01-14-13-22-40.bag  _2016-01-18-06-35-41.bag  _2016-01-20-11-00-44.bag
_2016-01-05-23-59-42.bag  _2016-01-14-13-30-23.bag  _2016-01-18-06-37-03.bag  _2016-01-20-13-28-10.bag.active
_2016-01-06-00-24-13.bag  _2016-01-14-13-38-59.bag  _2016-01-20-08-28-31.bag  _2016-01-20-13-28-10.bag.orig.active
_2016-01-14-12-50-16.bag  _2016-01-14-13-47-10.bag  _2016-01-20-08-35-36.bag  _2016-01-20-22-28-59.bag.active
_2016-01-14-12-51-39.bag  _2016-01-14-13-50-01.bag  _2016-01-20-09-58-33.bag …
```

[jsk_data] add bagfile_prefix arg for record.launch

---

jsk_topic_tools/CMakeLists.txt

This is critical because the xml file is declared in package.xml.
If I install jsk_topic_tools with apt, launch file with nodelet
won't work because of not found error.
Could you please merge this and release next version, soon?

[jsk_topic_tools] Fix missing installation of jsk_topic_tools_test_nodelet.xml

---

jsk_data/src/jsk_data/download_data.py

Somehow the empty directory is not copied to the release repository, and I think it's ok to not to include sample/trained data into deb package as for now...
https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_perception/sample/data
https://github.com/tork-a/jsk_recognition-release/tree/debian/indigo/trusty/jsk_perception/data
Current error message is something like this, and if we do not install jsk_perception,
```
make[4]: Leaving directory `/tmp/jsk_recognition-release/obj-x86_64-linux-gnu'
make -f CMakeFiles/install_sample_data.dir/build.make CMakeFiles/install_sample_data.dir/build
make[4]: Entering directory `/tmp/jsk_recognition-release/obj-x86_64-linux-gnu'
../scripts/install_sample_data.py
Checking md5sum of '/home/k-okada/.ros/data/2016-06-10-23-01-28_in_lab.bag'... …
```

catch if package is not found / do not download the data if the target directory is not writeable

---

jsk_tools/src/jsk_tools/migration.py

```python
import multiprocessing
import os
from jsk_tools.migration import ROSMsgMigration
THIS_FILE = os.path.realpath(__file__)
def main():
migration = ROSMsgMigration(
from_pkg='jsk_pcl_ros',
to_pkg='jsk_recognition_msgs',
msg_type='srv',
msg_files=[
'CallPolygon',
'CallSnapIt',
'CheckCircle',
'CheckCollision',
'EnvironmentLock',
'EuclideanSegment',
'ICPAlign',
'ICPAlignWithBox',
'PolygonOnEnvironment',
'RobotPickupReleasePoint',
'SetDepthCalibrationParameter',
'SnapFootstep',
'SwitchTopic',
'TowerPickUp',
'TowerRobotMoveCommand',
'TransformScreenpoint',
'UpdateOffset',
],
)
for root, dirnames, filenames in os.walk('src'):
if '/.git' in root:
continue
for fname in filenames:
fname = os.path.realpath(os.path.join(root, fname))
if fname == THIS_FILE:
continue
pool = …
```

[jsk_tools] Add utility class to migrate rosmsg

---

jsk_topic_tools/include/jsk_topic_tools/log_utils.h

See https://github.com/jsk-ros-pkg/jsk_common/issues/1461

[jsk_topic_tools] Deprecate JSK log macros and show warning

---

jsk_topic_tools/src/connection_based_nodelet.cpp
jsk_topic_tools/src/deprecated_relay_nodelet.cpp
jsk_topic_tools/src/standalone_complexed_nodelet.cpp

see
- https://github.com/jsk-ros-pkg/jsk_common/pull/1462
- https://github.com/jsk-ros-pkg/jsk_common/issues/1461

Stop using deprecated jsk_topic_tools/log_utils.h

---

jsk_tools/env-hooks/99.jsk_tools.sh

we can get self ip address which is used to access to specified ip (host ip) by:
```bash
$ ip -o -4 route get <host ip>
<host ip> via <gateway> dev wlan0  src <ip address>
```
however, if host ip is equal to self, prefix `local` is appended.
```bash
$ ip -o -4 route get <my ip>
local <my ip> via <gateway> dev wlan0  src <my ip>
```
I fixed to use `sed` to parse `src` ip address.

[jsk_tools][99.jsk_tools.sh] fix: issue #1472

---

jsk_data/package.xml

According to https://github.com/ros/rosdistro/pull/13397

Fix rosdep key: python-gdown -> python-gdown-pip

---

jsk_topic_tools/scripts/tf_to_transform.py

Rate can be 50 - 100 for example, but duration should be ~1 [s] even so. In
previous implementation, the duration will be 1/100 - 1/50 [s] and it is
too small to resolve tf.

[jsk_data] Use different value for duration and rate in tf_to_transform.py

---

jsk_data/launch/openni_play.launch
jsk_data/launch/openni_record.launch
jsk_data/package.xml

Record only depth image instead of pointcloud, but publish pointcloud on play.
support raw / compressed image.
tested with astra s
example usage:
```bash
roslaunch openni2_launch openni2.launch depth_registration:=true
roslaunch jsk_data openni_record.launch name:=icp_2d record_compressed_rgb:=true record_compressed_depth:=true rosbag_option:='--duration=120'
roslaunch jsk_data openni_play.launch name:=`pwd`/icp_2d_2017-03-25-20-52-46.bag rosbag_option:='--clock --loop'
```

[jsk_data] add openni_record.launch openni_play.launch

---

doc/jsk_topic_tools/class/connection_based_nodelet.md
jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h
jsk_topic_tools/src/connection_based_nodelet.cpp

Inspired from https://github.com/jsk-ros-pkg/jsk_recognition/pull/2043#issuecomment-289961945

[jsk_topic_tools][connection_based_nodelet] warn if onInitPostProcess is not called

---

jsk_tools/bin/ros_console.py

Because python-colorama is installed via apt
Close #1516
@k-okada maybe you can uncomment the run_depend of python-colorama when releasing

Remove import error message in ros_console.py

---

jsk_tools/CMakeLists.txt

currently we're asked to choose executable to run, can we remove `/share/jsk_tools/bin/ros_console.py` and others? if they are called like
```
`rospack find jsk_tools`/bin/ros_console
```
we'll have trouble.
```
$ rosrun jsk_tools ros_console.py  -n talker
[rosrun] You have chosen a non-unique executable, please pick one of the following:
1) /opt/ros/indigo/lib/jsk_tools/ros_console.py
2) /opt/ros/indigo/share/jsk_tools/bin/ros_console.py
```

CMakeLists.txt : fix install process, bin is already installed to /opt/ros/indigo/lib/jsk_tools/ directory

---

jsk_coordination_system/dynamic_tf_publisher/src/tf_publish.py

to supress message like
```
Traceback (most recent call last):
File "/opt/ros/indigo/lib/dynamic_tf_publisher/tf_publish.py", line 155, in <module>
pub.publish_and_sleep()
File "/opt/ros/indigo/lib/dynamic_tf_publisher/tf_publish.py", line 148, in publish_and_sleep
rospy.sleep(self.tf_sleep_time)
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 157, in sleep
raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
```

add ROSIntrupptException, not to show strage message on shutting down

---

jsk_topic_tools/test/test_connection.py

Close #1519
- modified:   test/test_connection.py

Test disconnection in test_connection.py

---

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h
jsk_topic_tools/src/connection_based_nodelet.cpp
jsk_topic_tools/src/jsk_topic_tools/transport.py

To see current subscribing state of a nodelet.

[jsk_topic_tools][connection_based_nodelet] add isSubscribed method

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/cfg/LightweightThrottle.cfg
jsk_topic_tools/include/jsk_topic_tools/lightweight_throttle_nodelet.h
jsk_topic_tools/package.xml
jsk_topic_tools/src/lightweight_throttle_nodelet.cpp

support changing `update_rate` using `dynamic_reconfigure`

[jsk_topic_tools][LightweightThrottle] dynamic change update_rate

---

jsk_data/src/jsk_data/download_data.py

**Major Update**
- Change permission of not only downloaded data but also decompressed data
**Minor fix**
- Fix: `ZipFile` does not have a method `getnames`

[jsk_data][download_data.py] chmod decompressed data

---

jsk_network_tools/src/silverhammer_highspeed_internal_receiver.cpp

**Before**
```
Warnings   << jsk_network_tools:make /home/wkentaro/Projects/jsk/logs/jsk_network_tools/build.make.000.log
/home/wkentaro/Projects/jsk/src/jsk-ros-pkg/jsk_common/jsk_network_tools/src/silverhammer_highspeed_internal_receiver.cpp: In member function ‘void jsk_network_tools::SilverhammerHighspeedInternalReceiver::threadFunc()’:
/home/wkentaro/Projects/jsk/src/jsk-ros-pkg/jsk_common/jsk_network_tools/src/silverhammer_highspeed_internal_receiver.cpp:132:167: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
ROS_INFO("seq_id := %lu, packet_array.size() := %lu, packet_num := %lu",
```

Fix warning about %d vs %lu in silverhammer_highspeed_internal_receiver

---

jsk_ros_patch/image_view2/CMakeLists.txt

pcl関連（pcl / pcl_ros / perception_pcl / pcl_convertions）をソースから入れた環境でビルドしてみたら，
```
image_view2.h:63:31: fatal error: pcl_ros/publisher.h: No such file or directory
```
と怒られてしまいましたので，報告しておきます．
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_ros_patch/image_view2/image_view2.h#L63
※ pcl関連をaptから入れたら発生しないです
--- 
以下試行錯誤メモ: thanks to @aginika 
- 2と3は要らない気がする．4が大事そう．
- ``/etc/ld.so.conf``を見ると``/usr/local/lib``（srcで入れると入る方）が``/usr/lib``（aptで入れると入る方）より優先的に見られるようになっているので，変なことしなければaptとsrcが混ざっていても問題ない
- ただ，実際に使われるのはキャッシュ``/etc/ld.so.cache``なので，pclをsrcで入れなおしただけでは上手く行かなかったっぽい．``ldconfig``をしてキャッシュを上書きすればcatkin cleanいらなかったかも．
---
1. pcl1.8をソースから入れる
```bash
git clone https://github.com/PointCloudLibrary/pcl.git
cd pcl
mkdir build; cd build
ccmake .. # build_gpuをonにする
make
sudo make install
```
- …

need to find pcl_ros for image_view2

---

jsk_tools/src/jsk_tools/sanity_lib.py

For https://github.com/start-jsk/jsk_apc/pull/2561

Make TopicPublishedChecker run in parallel

---

jsk_data/src/jsk_data/download_data.py

Current implementation exits with OSError, but I'd like to pass the exception because it is an expected error.
```
Errors << jsk_apc2016_common:make /home/travis/ros/ws_jsk_apc/logs/jsk_apc2016_common/build.make.000.log
Traceback (most recent call last):
File "/home/travis/ros/ws_jsk_apc/src/jsk_apc/jsk_apc2016_common/scripts/install_sample_data.py", line 19, in <module>
main()
File "/home/travis/ros/ws_jsk_apc/src/jsk_apc/jsk_apc2016_common/scripts/install_sample_data.py", line 14, in main
extract=True,
File "/opt/ros/indigo/lib/python2.7/dist-packages/jsk_data/download_data.py", line 119, in download_data
os.makedirs(cache_dir)
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/travis/.ros/data/jsk_apc2016_common'
```

Skip mkdir failures that can be caused by multiprocessing

---

jsk_topic_tools/src/jsk_topic_tools/transport.py

This checks some common mistakes when users implement Python node using `jsk_topic_tools.ConnectionBasedTransport`.
-  Check if publishers exist to avoid implementation failures
Someone uses rospy.Publisher instead of ConnectionBasedTransport.advertise.
-  Use ABCMeta to avoid unexpected usage of ConnectionBasedTransport
Someone uses this class without any subscriptions, and in that case this
class should not be used in general. ABCMeta forces user to overwrite the abstract methods (ex. `subscribe`, `unsubscribe`).

Validate implementation of child class of ConnectionBasedTransport

---

doc/jsk_topic_tools/lib/stealth_relay_nodelet.md
jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/include/jsk_topic_tools/stealth_relay.h
jsk_topic_tools/jsk_topic_tools_nodelet.xml
jsk_topic_tools/src/stealth_relay_nodelet.cpp
jsk_topic_tools/test/test_stealth_relay.py
jsk_topic_tools/test/test_stealth_relay.test

This node relays topic from `~input` and `~output` as normal `rostopic relay`, but it does not increment number of subscribers (actually increments number of subscribers, but not looks like so)

jsk_topic_tools: add stealth_relay for silently subscribing topic

---

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h

`advertiseCamera` with image_transport occurs infinite loop

jsk_topic_tools: connection_based_nodelet: fix typo in advertiseCamera

---

jsk_tools/env-hooks/99.jsk_tools.sh

Fixes https://github.com/jsk-ros-pkg/jsk_common/issues/1559
c.f.:
https://askubuntu.com/questions/702161/why-is-my-interface-now-wlp2s0-instead-of-wlan0

Support network interface name convention from ubuntu 15.10

---

.travis.yml

According to offline talk with @k-okada, we're now considering about dropping hydro.
If this test does not pass, only drop hydro and keep `jsk_travis` unchanged.

travis: drop hydro

---

.travis.yml

Close https://github.com/jsk-ros-pkg/jsk_common/pull/1552
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1566
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1563
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1562
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1555
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1554
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1552

Fix travis push build: Travis + Docker + jsk_travis==0.4.34

---

doc/jsk_topic_tools/lib/stealth_relay_nodelet.md
jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/cfg/StealthRelay.cfg
jsk_topic_tools/include/jsk_topic_tools/stealth_relay.h
jsk_topic_tools/src/stealth_relay_nodelet.cpp
jsk_topic_tools/test/test_stealth_relay.py
jsk_topic_tools/test/test_stealth_relay.test

This pull request is for updating `jsk_topic_tools/StealthRelay` nodelet:
- Support dynamic reconfigure
- Keep consistency with upstream (param name etc..)
- Cleanup internal function
- Add option `enable_monitor` to toggle monitoring
- update test codes

jsk_topic_tools: stealth_relay add options as dynamic_reconfigure

---

jsk_data/src/jsk_data/download_data.py

- Fix: Make sure to change permission even if downloading is interrupted
- Fix: Check file permission before `chmod` since `os.chmod` fails when changing the permission of files which were already changed.

jsk_data: download_data.py: ensure chmod downloaded data if possible

---

jsk_tools/bin/roscore_regardless.py
jsk_topic_tools/src/jsk_topic_tools/master_util.py

- jsk_topic_tools: `isMasterAlive` was not working correctly.
- jsk_tools: `roscore_regardless.py`
- Added feature to pass signals sent to parent to children
- Set proper attributes on spawn child process
- Clean and quiet log printing
- Killing by gradually escalating signals like `roslaunch`

Fix roscore regardless

---

doc/jsk_topic_tools/class/connection_based_nodelet.md
doc/jsk_topic_tools/class/diagnostic_nodelet.md
jsk_topic_tools/include/jsk_topic_tools/diagnostic_nodelet.h
jsk_topic_tools/include/jsk_topic_tools/diagnostic_utils.h
jsk_topic_tools/src/diagnostic_nodelet.cpp
jsk_topic_tools/src/diagnostic_utils.cpp

This PR adds `~use_warning` parameter to display diagnostic messages on warning level instead of error level on `DiagnosticNodelet`.

jsk_topic_tools: add option to display diagnostic messages on warning level

---

jsk_topic_tools/src/diagnostic_nodelet.cpp

In this [PR](https://github.com/jsk-ros-pkg/jsk_common/pull/1585), 
default of diagnostic error level have been mistakenly changed to ```warn```.
This PR fixes warn level.

[jsk_topic_tools] Fixed use_warn option

---

jsk_topic_tools/src/jsk_topic_tools/transport.py

On Kinetic we have below error, and this PR fixes it by resetting the timer.
```
[ERROR] [1535796247.786932, 1535792085.063646]: [/get_heightmap] [sleep] ROS time moved backwards: 1.407559397s
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 226, in run
r.sleep()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 103, in sleep
sleep(self._remaining(curr_time))
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 164, in sleep
raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
ROSTimeMovedBackwardsException: ROS time moved backwards
Exception in thread Thread-4: …
```

Add reset to Timer in ConnectionBasedTransport

---

doc/jsk_data/node_scripts/data_collection_server.rst
jsk_data/CMakeLists.txt
jsk_data/node_scripts/data_collection_server.py
jsk_data/package.xml
jsk_data/tests/data_collection_server.test
jsk_data/tests/test_data_collection_server.py
jsk_topic_tools/scripts/static_image_publisher.py

Close https://github.com/jsk-ros-pkg/jsk_common/pull/1598
Close #1596

Add test for data_collection_server

---

jsk_ros_patch/image_view2/image_view2.cpp

```could not found``` is grammatically incorrect.

[image_view2/image_view2.cpp] Correct grammer. 'could not found' -> could not find'

---

jsk_data/src/jsk_data/download_data.py

Fix http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__jsk_pcl_ros_utils__ubuntu_xenial_amd64__binary/132/console

check if the pkg exists and path is writable

---

jsk_data/src/jsk_data/download_data.py

ex; gdown is pip distributed so that we can not use this within de build farm

check if wget/gdown command exists

---

jsk_data/src/jsk_data/download_data.py

By applying this Pull Request, `download_data.py` generates error message when downloaded file's md5 is incorrect.

[download_data.py] generate error log when downloaded fils's md5 is incorrect

---

jsk_topic_tools/include/jsk_topic_tools/stealth_relay.h
jsk_topic_tools/src/stealth_relay_nodelet.cpp

Currently, copy constructor of each message is called twice on callback which causes unexpected pointer release.

stealth_relay_nodelet: fix error double free or corruption (fasttop)

---

jsk_topic_tools/sample/standalone_complexed_nodelet/simple.launch
jsk_topic_tools/src/standalone_complexed_nodelet.cpp

```yaml
nodelets:
-  name: node_name
type: nodelet_type
remappings:
- from: from_topic
to: to_topic
- from: from_topic
to: to_topic
params:  # This is supported in this PR.
- name: approximate_sync
value: true
- name: queue_size
value: 100
-  name: node_name2
type: nodelet_type2
if: false
-  name: node_name3
type: nodelet_type3
unless: false
```

standalone_complexed_nodelet: add `params` key for each nodelet

---

jsk_data/src/jsk_data/download_data.py

If contents of tar/zip archive already exist, `download_data` will skip extracting them by this PR.

[jsk_data] Skip extracting files which already exist

---

jsk_topic_tools/src/deprecated_relay_nodelet.cpp

this error is printed into `warn` in high frequency because `warn` is printed everytime when the topic is subscribed.
I change it to print only once when the node starts.

[deprecated_relay] print warning message only when relayed topic is subscribed

---

doc/jsk_tools/cltools/roscore_regardless.md
jsk_tools/bin/roscore_regardless.py

When using roscore_regardless.py with roslaunch, roscore_regardless.py may send SIGTERM to roslaunch before the roslaunch sends SIGTERM to the child processes. 
In that case, the processes invoked by roslaunch can be zombie because the parent roslaunch is killed by roscore_regardless.py.
* Add `--sigint-timeout` and `--sigterm-timeout` options to change duration to escalate signals.
* Increase default timeout values of `--sigint-timeout` and `--sigterm-timeout` from 10 seconds and 2 seconds to 20 seconds and 10 seconds respectively because they should be longer than the values in roslaunch. In roslaunch code, [`_TIMEOUT_SIGINT` is 10 seconds](https://github.com/ros/ros_comm/blob/6b9efd56d6882d1c017152ba11a5780a1496b30b/tools/roslaunch/src/roslaunch/nodeprocess.py#L58) and …

[jsk_tools/roscore_regardless.py] Do not send SIGTERM before roslaunch sends SIGTERM

---

doc/jsk_tools/cltools/roscore_regardless.md
jsk_tools/bin/roscore_regardless.py
jsk_topic_tools/src/jsk_topic_tools/master_util.py

* Sometimes ping is not stable. `--ping-trials` option enables
roscore_regardless.py to verify host computer of rosmaster is alive
by multi-times ping commands.

[jsk_tools] Add --ping-trials option to roscore_regardless.py

---

jsk_topic_tools/src/jsk_topic_tools/log_utils.py

cpickle is no more used in python3

[jsk_topic_tools] import _pickle as pickle for python3

---

jsk_data/src/jsk_data/download_data.py

```
process[data_collection_server-5]: started with pid [11865]
Traceback (most recent call last):
File "/home/wkentaro/xxxxxxxxxxx/src/jsk-ros-pkg/jsk_common/jsk_data/node_scripts/data_collection_server.py", line 26, in <module>
from jsk_data.cfg import DataCollectionServerConfig
File "/home/wkentaro/xxxxxxxxxxx/devel/lib/python3/dist-packages/jsk_data/__init__.py", line 35, in <module>
exec(__fh.read())
File "<string>", line 1, in <module>
File "/home/wkentaro/xxxxxxxxxxx/src/jsk-ros-pkg/jsk_common/jsk_data/src/jsk_data/download_data.py", line 73
os.chmod(os.path.abspath(fname), 0777)
^
SyntaxError: invalid token
```

Fix download_data.py for Python3

---

jsk_topic_tools/include/jsk_topic_tools/synchronized_throttle.h
jsk_topic_tools/src/synchronized_throttle_nodelet.cpp

In SynchronizedThrottle, if node is killed, the following error occurs.
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted
```
This PR fixes this behavior.
Also see https://github.com/ros/ros_comm/issues/720 .

[jsk_topic_tools/SynchronizedThrottle] Reset sync policy in destructor

---

jsk_ros_patch/image_view2/README.md
jsk_ros_patch/image_view2/sample/sample_rectangle_mouse_event.launch
jsk_ros_patch/image_view2/test/rectangle_mouse_event.launch

In this pull request, I did
- separate `test/rectangle_mouse_event.launch` into sample launch and test launch.
- update README about the sample launch
I think sample launch file is needed for image_view2 beginners.
We can easily understand `Interactive Modes` and `image_view2/ImageMarker2`
Interactive Modes
`image_view2/ImageMarker2`

Add sample code for image_view2

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h
jsk_topic_tools/include/jsk_topic_tools/nodelet_version.h.in
jsk_topic_tools/package.xml
jsk_topic_tools/src/connection_based_nodelet.cpp

THIS IS URGENT.
This PR fixes build error in `ConnectionBasedNodelet` introduced in #1647 .
It was totally my misunderstanding about cmake and build system.
I fix it to build properly, and I also check the method exists in `libjsk_topic_tools.so`.
I add `jsk_topic_tools/nodelet_version.h` to check nodelet version in `jsk_topic_tools`.
`warnNoRemap` exists
```
[knorth55][melodic-p50][/opt/ros/melodic/lib]
$ dpkg -l | grep jsk-topic-tools
ii  ros-melodic-jsk-topic-tools                                      2.2.10-0bionic.20200402.152204                   amd64        jsk_topic_tools
[knorth55][melodic-p50][/opt/ros/melodic/lib]
$ nm -gD libjsk_topic_tools.so | grep connectionbasednodelet -i | grep warn
00000000001217e0 T _ZN15jsk_topic_tools22ConnectionBasedNodelet11warnNoRemapESt6vectorINSt …
```

[jsk_topic_tools] add NODELET_VERSION_MINIMUM and fix nodelet version to build properly

---

doc/index.rst
doc/jsk_network_tools/index.rst
doc/jsk_network_tools/scripts/network_status.md
jsk_network_tools/scripts/network_status.py

this PR adds `~skip_interfaces` param in `jsk_network_tools/network_status.py`
You can specify skipping interfaces as follows:
```xml
<launch>
<node name="network_status" pkg="jsk_network_tools" type="network_status.py">
<rosparam>
skip_interfaces:
- docker0
- lo
- eno2
</rosparam>
</node>
</launch>
```
I also add doc for `jsk_network_tools/network_status.py`

[jsk_network_tools] add skip_interfaces param in network_status.py

---

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h

* Add latch argument to advetiseImage and advertiseCamera instead of
reading latch parameter from ros server in order to set different latch
parameter for each publisher in one nodelet.

Add latch argument to advetiseImage and advertiseCamera

---

doc/jsk_topic_tools/lib/relay_nodelet.md
jsk_topic_tools/include/jsk_topic_tools/relay_nodelet.h
jsk_topic_tools/src/relay_nodelet.cpp

This allows us to make any topic latched. In my use case, I wanted to make `jsk_pcl/extract_indices/output` to be latched.

Add latch mode to jsk_topic_tools/Relay

---

jsk_ros_patch/image_view2/CMakeLists.txt
jsk_topic_tools/CMakeLists.txt

Same fix as https://github.com/jsk-ros-pkg/jsk_visualization/pull/780
This PR is fix for error about ccache like reported below:
https://github.com/CoatiSoftware/Sourcetrail/issues/1081

Set ccache prefix only for cmake <= 3.4

---

audio_video_recorder/CMakeLists.txt
audio_video_recorder/README.md
audio_video_recorder/include/audio_video_recorder/audio_video_recorder.h
audio_video_recorder/launch/audio_video_recorder.launch
audio_video_recorder/package.xml
audio_video_recorder/sample/pr2_audio_video_recorder.launch
audio_video_recorder/sample/sample_audio_video_recorder.launch
audio_video_recorder/src/audio_video_recorder.cpp
jsk_common/package.xml

add `audio_video_recorder` package in `jsk_common`
orginally developed in https://github.com/knorth55/audio_video_recorder
[//]: ![](https://github.com/knorth55/jsk_common/raw/audio-video-recorder/audio_video_recorder/.media/pr2_sample.gif)
https://user-images.githubusercontent.com/9300063/113512847-8e9f2600-95a1-11eb-8bed-17dcf9e08907.mp4
[Full video on Google Drive](https://drive.google.com/file/d/1TWnRKbOdq6jPza82eNhhjn56lQXRxWjl/view?usp=sharing)
cc. @nakaotatsuya

add audio_video_recorder in jsk_common

---

jsk_data/node_scripts/data_collection_server.py

As to data_collection_server, wait_service_request for request method was implemented by https://github.com/jsk-ros-pkg/jsk_common/pull/1669 . 
So I apply it to the other methods such as timer method and all method.

[jsk_data] add wait_timer for timer method

---

jsk_tools/package.xml

add `python3-progressbar` and `python3-rosdep` for noetic
https://build.ros.org/job/Ndev__jsk_common__ubuntu_focal_amd64/29/console

[jsk_tools] use python3-progressbar and python3-rosdep for noetic

---

jsk_data/node_scripts/data_collection_server.py
jsk_data/tests/test_data_collection_server.py

Now 20.04 travis fails. 
https://github.com/jsk-ros-pkg/jsk_common/runs/6300763557?check_suite_focus=true#step:7:9754
This is because the result of the `mktemp -d` command** contains newline.
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_data/tests/data_collection_server.test#L30
This PR fix the test.

[jsk_data] Strip newline at test code.

---

jsk_data/tests/test_data_collection_server.py
jsk_topic_tools/test/test_connection.py
jsk_topic_tools/test/test_connection_based_nodelet.test
jsk_topic_tools/test/test_connection_based_transport.test
jsk_topic_tools/test/test_stealth_relay.py
jsk_topic_tools/test/test_stealth_relay.test
jsk_topic_tools/test/test_topic_buffer_fixed_rate.test

Tests in `jsk_common` tends to fail.
https://github.com/jsk-ros-pkg/jsk_common/runs/6567117461?check_suite_focus=true
https://github.com/jsk-ros-pkg/jsk_common/runs/6549477630?check_suite_focus=true
https://github.com/jsk-ros-pkg/jsk_common/runs/6549477789?check_suite_focus=true
This is because programs that depend on the performance of the computer or sleep cannot pass the test in some cases.
This PR makes it easier to pass the test by making the following changes.
* [jsk_data/tes_data_collection_server] Check if text and yaml or text and image are saved in the subdirectory of `save_dir`.
* [jsk_topic_tools/test_stealth_relay] Fix test by waiting topic connection istead of rospy.sleep
* [jsk_topic_tools/test_stealth_relay] Increased stealth relay time and retry count
* …

Loose test failed

---

jsk_topic_tools/include/jsk_topic_tools/diagnostic_nodelet.h
jsk_topic_tools/include/jsk_topic_tools/relay_nodelet.h
jsk_topic_tools/src/diagnostic_nodelet.cpp
jsk_topic_tools/src/relay_nodelet.cpp

If the diagnostics nodelet is currently subscribed,but the publish function is not executed (`vital_checker->poke()` is not executed), it publishes diagnostics with an error level.
This publishes error level diagnostics only at the beginning because poke is not called when subscribing starts.
This is to change to output diagnostics at the OK level by inserting a poke when switching from the not subscribed state to the subscribed state.

[jsk_topic_tools/diagnostics_nodelet] Poke when start subscribing.

---

doc/jsk_topic_tools/class/python_connection_based_transport.md
jsk_topic_tools/src/jsk_topic_tools/transport.py

Update the time of `last_published_time` to make it possible to take the difference time between the time of start subscribing and the current time.
`ConnectionBasedTransport` checks if topic is input and output normally.
https://github.com/jsk-ros-pkg/jsk_common/blob/df29bfbe32b07045be2a8f2a951a091a4f3c7d1e/jsk_topic_tools/src/jsk_topic_tools/transport.py#L176-L195
`self._connection_status` changes to `SUBSCRIBED` when node are subscribed.
The `is_running` function checks `last_published_time` and is `True` if it is published within the `1 / vital_rate` time.
If it hasn't been subscribed for a while now, `is_running` will always be `False` at first because `last_published_time` will not be updated all the time when it is not subscribed.
Related to …

[jsk_topic_tools/connection_based_transport] Update the time of last_published_time

---

doc/jsk_topic_tools/class/hz_measure_nodelet.md
jsk_topic_tools/include/jsk_topic_tools/hz_measure_nodelet.h
jsk_topic_tools/src/hz_measure_nodelet.cpp

Enable publishing diagnostics on `HzMeasureNodelet`.
This PR also adds a document.
The difference from `sanity_diagnostics.py` is that you can ignore the communication overhead when using it with nodelet.
```
This node publishes `hz` of target topic and `diagnostics`.
User can specify `~warning_hz` param.
If target `hz` is smaller than `~warning_hz`, this node outputs `diagnostics` at `WARN` level (if `~use_warn` is `True`) or `ERROR` level.
```
For example, use it when you want to monitor the topic in the nodelet.
At first, the topic (`/head_camera/depth_registered/hw_registered/image_rect_raw`) like this works with normal hz.
If hz drops for some reason, it will output error level diagnostics as follows:

[jsk_topic_tools/HzMeasureNodelet] Add diagnostics to monitor hz

---

doc/jsk_tools/test_nodes/test_topic_published.rst
jsk_tools/src/test_topic_published.py
jsk_tools/test/test_topic_published.launch

Added condition option to check if the output topic value is correct.
The descriptions are followings.
```
- ``~condition_%d`` (``str``, Default: ``None``, Optional)
Check bool value condition using the given Python expression.
The Python expression can access any of the Python builtins plus:
``topic`` (the topic of the message), ``m`` (the message) and ``t`` (time of message).
For example, topic is ``std_msgs/String`` and if you want to check whether a sentence is a ``hello``, you can do the following.
.. code-block:: bash
condition_0: m.data == 'hello'
If you want to check the frame id of the header, you can do the following.
.. code-block:: bash
condition_0: m.header.frame_id in ['base', 'base_link']
Note that, use escape sequence when using the following symbols ``<(&lt;)``, …
```

[jsk_tools/test_topic_published.py] Add condition_%d option for checking topic value

---

doc/jsk_tools/scripts/sanity_diagnostics.md
jsk_tools/sample/sample_sanity_diagnostics.launch
jsk_tools/src/sanity_diagnostics.py

sanity diagnostics status in rqt_robot_monitor turns on and off.
In this PR, I separate topic and node check frequency and diagnostics publish frequency.
- Check topic and node at low frequency to reduce CPU usage
- Publish diagnostics at high frequency to avoid the above problem.
Currently, when I run `roslaunch jsk_tools sample_sanity_diagnostics.launch`, `/diagnostics` topic is published at more than 1 Hz but `check_topic()` and `check_node()` methods are called at 0.1 Hz.

[jsk_tools] Seperate sanity check frequency and diagnostics publish frequency

---

jsk_topic_tools/CMakeLists.txt
jsk_topic_tools/include/jsk_topic_tools/jsk_topic_tools_version.h.in

I add `version.h` for `jsk_topic_tools` to check version for build.
`jsk_topic_tools` has base class such as `DiagnosticNodelet` and `ConnectionBasedNodelet`.
For example, nodes in `jsk_recognition` are using those notelets.
This PR is useful to check `jsk_topic_tools` version.
Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712

[jsk_topic_tools] Add header file to check jsk_topic_tools' version

---

jsk_topic_tools/src/timered_diagnostic_updater.cpp

The timed diagnostic updater used in `DiagnosticNodelet` and `relaynodelet` updates the diagnostic for a predetermined duration using timer.
However, the diagnostic_updater that TimeredDiagnosticUpdater has determines whether an update is actually performed based on its own timer in the update function.
https://github.com/ros/diagnostics/blob/dbc73ff508813ec13eaf23594006ccb9b61d083c/diagnostic_updater/include/diagnostic_updater/diagnostic_updater.h#L383-L392
```
void update()
{
ros::Time now_time = ros::Time::now();
if (now_time < next_time_) {
// @todo put this back in after fix of #2157 update_diagnostic_period(); // Will be checked in force_update otherwise.
return;
}
force_update();
}
```
Since TimedDiagnosticUpdater is already managed as a timer, diagnostic_updater_->force_update …

[jsk_topic_tools/timered_diagnostics_updater] Use force_update instead of update because of update called using TimeredDiagnosticUpdater's timer

---

jsk_topic_tools/CMakeLists.txt

Generate jsk_topic_tools_version.h without calling catkin_package_xml.
https://github.com/ros/catkin/blob/2612c4ce82a285cac13263576f8a85b8a6d6cd3d/cmake/catkin_package.cmake#L97-L100
Note that catkin_package_xml needs to be called, but it is called in catkin_package.
Related to https://github.com/jsk-ros-pkg/jsk_common/pull/1753

[jsk_topic_tools/version] Generate jsk_topic_tools_version.h without calling catkin_package_xml.

---

jsk_tools/src/sanity_diagnostics.py

Modified the timing of updating timestamp and states for each topic and each node.
Now all topics are managed in one timestamp, so when one topic is updated, the others are not checked.
This PR checks each topic correctly by maintaining a timestamp for each topic.
This PR is tested on PR1040 https://github.com/knorth55/jsk_common/pull/25

[jsk_tools/sanity_diagnostics.py] Modified the timing of updating

---

jsk_topic_tools/include/jsk_topic_tools/diagnostic_nodelet.h
jsk_topic_tools/src/diagnostic_nodelet.cpp

Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712
The jsk nodes use `ConnectionBasedNodelet` and `DiagnosticsNodelet`.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712#discussion_r918957879
If we want to write the following, we need to create a constructor with no arguments in DiagnosticsNodelet.
```
#if  defined(JSK_TOPIC_TOOLS_VERSION) and JKS_NODELET_VERSION_MINIMUM(2,2,13))
#define jsk_topic_tools::NODLET jsk_topic_tools::ConnectionBasedNodelet
#else
#define jsk_topic_tools::NODLET jsk_topic_tools::DiagnosticNodelet
#endif```

[jsk_topic_tools/DiagnosticsNodelet] Enable constructor without name argument

---

doc/jsk_topic_tools/scripts/boolean_node.rst
jsk_topic_tools/scripts/boolean_node.py

Changed boolean node to evaluate condition each time a topic is published.
For example, a condition that checks whether a certain topic has arrived within one second look like this.
```
<node name="shutdown_selector"
pkg="jsk_topic_tools" type="boolean_node.py"
output="screen"
clear_params="true"
respawn="true" >
<remap from="~input1" to="$(arg battery_state_topic)" />
<remap from="~input2" to="$(arg shutdown_unchecked_topic)" />
<remap from="~output/and" to="/execute_shutdown" />
<rosparam>
number_of_input: 2
input1_condition: "m.is_charging is False"
input2_condition: "(rospy.Time.now() - t).to_sec() &lt; 1.0"
</rosparam>
</node>
```
https://github.com/jsk-ros-pkg/jsk_robot/pull/1570

[jsk_topic_tools] Eval at every timer callback

---

jsk_topic_tools/src/diagnostic_nodelet.cpp
jsk_topic_tools/src/diagnostic_utils.cpp

Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712 and https://github.com/jsk-ros-pkg/jsk_common/pull/1761
The DiagnosticNodelet outputs diagnostic messages.
However, the name has been specified by the developer.　https://github.com/jsk-ros-pkg/jsk_common/pull/1761
[This PR](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712) allows the user to use connection based nodelets and diagnostics nodelets depending on the version of jsk_topic_tools.
I have also changed the format to make the numbers easier to read.
[jsk_recognition package's PR](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712) assumes that these changes will be incorporated in the next released version (`2.2.13`).

[jsk_topic_tools/DiagnosticNodelet] Use node name for diagnostic message

---

jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_video.py

`bag_to_video` throw `StopInteration` signal when there is no `next` in iterator.
This occurs when all images has 0 timestamp.
This PR avoid the error and skip the topic when all timestamp is zero.

catch StopIteration when all images do not have stamp

---

jsk_rosbag_tools/CMakeLists.txt
jsk_rosbag_tools/requirements.in
jsk_rosbag_tools/requirements.in.python2

this PR solves #1780 
`typeDict` is deprecated in `numpy>=1.21.0` in `scipy`
For python3, I install `scipy` in `catkin_virtualenv` to upgrade `scipy`.
https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict/74969328#74969328
scipy version should be `1.9.0` because of `openblas` problem with `meson`.
https://github.com/scipy/scipy/issues/16308
For python2, I install `numpy<1.21.0` to avoid attribute error.
So I made two requirements for `python2` and `python3`.
- python3:
- `scipy<1.9.0` (because of meson build error)
- `numpy>=1.21.0` (scipy requires this version)
- python2
- `scipy` from apt
- `numpy<1.21.0`(because of typeDict attribute error)
this PR also specify the python interpreter as `python2` for melodic.

[jsk_rosbag_tools] set python_interpreter python2 for melodic, install scipy<1.9.0+numpy>=1.21.0 for python3  and apt scipy+numpy<1.21.0 for python2

---

jsk_rosbag_tools/package.xml

In noetic, the following error occurred when I executed `rosdep install`.
This PR avoids this error.
```
tsukamoto@tsukamoto-desktop-ryzen ~/ros/fetch_ws/src/jsk-ros-pkg/jsk_common/jsk_rosbag_tools (develop/fetch %=) 
$ rosdep install -y -r --from-paths . --ignore-src
executing command [sudo -H apt-get install -y python-catkin-pkg-modules]
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
E: パッケージ python-catkin-pkg-modules が見つかりません
ERROR: the following rosdeps failed to install
apt: command [sudo -H apt-get install -y python-catkin-pkg-modules] failed
apt: Failed to detect successful installation of [python-catkin-pkg-modules]
```

[jsk_rosbag_tools] Use python3-catkin-pkg-modules when python3 is used

---

doc/jsk_topic_tools/lib/passthrough_nodelet.md

This PR fixes jsk_topic_tools/Passthrough documentation.
In https://github.com/jsk-ros-pkg/jsk_common/blob/78faabe470fe02567e215a05a752e7c1d97e16a6/jsk_topic_tools/launch/passthrough_sample.launch  , 
remap topic uses `~` something like '~input', so input topic and output topic don't have a namespace from the node name.

[doc] Fix jsk_topic_tools/Passthrough doc Usage section

---

jsk_topic_tools/scripts/boolean_node.py

This PR avoids `ROSTimeMovedBackwardsException` when boolean_node is running with rosbag with --loop option.
[rospy/timer.py](https://github.com/ros/ros_comm/blob/845f74602c7464e08ef5ac6fd9e26c97d0fe42c9/clients/rospy/src/rospy/timer.py#L204C49-L204C49)

[jsk_topic_tools] Add reset option to use boolean_node with rosbag

---

jsk_rosbag_tools/requirements.in

Related to #1798 
In the course of addressing a build failure related to dependency resolution within our `jsk_rosbag_tools` package, we encountered an error indicating that `pip-compile` was unable to properly identify the version of the `Pillow` package required by `imageio==2.34.0` as part of the `moviepy==1.0.3` dependency. The error specifically pointed out that the package name or version was not recognized properly, which led to a halt in the dependency resolution process and subsequently the build process.
To resolve this issue, we've explicitly pinned the `Pillow` version to `8.4.0` in the `requirements.in` file. This action was taken after thoroughly investigating the underlying problem, which suggested that an explicit declaration could help `pip-compile` in resolving the …

[jsk_rosbag_tools] Fixed pillow version

---

jsk_network_tools/CMakeLists.txt
jsk_topic_tools/CMakeLists.txt

To fix the error `/usr/bin/env: ‘python’: No such file or directory`

use catkin_install_python to install python scripts

---

jsk_data/src/jsk_data/download_data.py

This PR solves 2 problems. 
- `rospkg.RosPack.pkg_name` doesn't return the current building package's src directory when `colcon build` . So while building the package like `jsk_perception` , `download_data` tries to download in `/opt/ros/share/jsk_perception` and fails because of permission error. This PR fixes it.
- When using `colcon build`, `$ROS_PACKAGE_PATH` always returns the workspace's install path, not the `src` directory. This PR downloads data in the `install/<some path>/share` directory for `rospkg` to find the appropriate path. 
cc: @sugikazu75

[colcon][jsk_data] Support download_data with colcon

---

jsk_data/src/jsk_data/cli.py
jsk_data/src/jsk_data/ssh.py

- stdout.read() returns a bytes object in Python 3, whereas in Python 2, it returned a str
-
The error indicates that the new version of Paramiko (2.6.0) is stricter about host key checking, requiring the server to be present in the known_hosts file by default. This is a security feature to prevent man-in-the-middle attacks.
Closes #1792

[jsk_data] Automatically add the host key and Check stdout.read() type

---

jsk_topic_tools/src/connection_based_nodelet.cpp

jsk_peceptino could not find isSubscribed if it is defined as inline
```
usr/lib/x86_64-linux-gnu/libopencv_phase_unwrapping.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_optflow.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_ximgproc.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_video.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_dnn.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_features2d.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_flann.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_photo.so.4.5.4d /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.4.5.4d …
```

remove inline from ConnectionBaseNodelet::isSubscribed()

---

jsk_rosbag_tools/requirements.in.python2

update jsk_travis and fix error on `jsk_rosbag_tools/requirements.in.python2`, Working installed pip packages as follows.
```
certifi==2025.7.14        # via requests
charset-normalizer==3.4.2  # via requests
decorator==4.4.2          # via moviepy
idna==3.10                # via requests
imageio-ffmpeg==0.5.1     # via moviepy
imageio==2.35.1           # via moviepy
moviepy==1.0.3            # via -r requirements.in
numpy==1.24.4             # via -r requirements.in, imageio, moviepy, scipy
pillow==8.4.0             # via -r requirements.in, imageio
proglog==0.1.12           # via moviepy
requests==2.32.4          # via moviepy
scipy==1.8.1              # via -r requirements.in
tqdm==4.67.1              # via moviepy, proglog
urllib3==2.2.3            # via requests
```

update jsk_travis 0.5.28 (new ROS repository key)
