jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
=> [image_view2] Add new interaction mode to image_view 2 to select foreground and background by rectangular region

jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
To avoid difficult problem of highgui...
=> [image_view2] Call GUI functions from main thread

bayesian_belief_networks/setup.py
=> check debian_version to see site/dist packages

jsk_network_tools/CMakeLists.txt, jsk_network_tools/launch/simple_silverhammer_sample.launch, jsk_network_tools/msg/FC2OSC.msg, jsk_network_tools/msg/OSC2FC.msg, jsk_network_tools/scripts/silverhammer_lowspeed_gateway.py, jsk_network_tools/setup.py, jsk_network_tools/src/jsk_network_tools/silverhammer_util.py, jsk_network_tools/test/fc2osc_publisher.py, jsk_network_tools/test/osc2fc_publisher.py
> Bang, bang, Maxwell's silver hammer came down upon his head (do do do do do)
>>  [The Beatles, Maxwell's Silver Hammer](https://www.youtube.com/watch?v=vvBSQ1RsAzc)
Silverhammer script is a simple network script written in Python to communicate over low-bandwidth environment.
Target environment is 2kbps.
Currently only low-bandwidth communication is supported. High speed network is not yet supported.
silver hammer can only send FC2OSC.msg and OSC2FC.msg.
It will automatically pack/unpack the mssage in the most efficient way and send it over UDP protocol.
=> [jsk_network_tools] script to communicate over low-bandwidth network.

3rdparty/downward/CMakeLists.txt
downward server is always down
=> [downward] Ignore error when building downward.

jsk_network_tools/msg/FC2OCSLargeData.msg, jsk_network_tools/scripts/silverhammer_highspeed_receiver.py, jsk_network_tools/scripts/silverhammer_highspeed_streamer.py, jsk_network_tools/src/jsk_network_tools/silverhammer_util.py, jsk_network_tools/test/ocs2fc_publisher.py
new script to communicate over one-way highspeed-link
* Directly send serialized ROS message over UDP
* The message type is called FC2OCSLargeData.msg
* The topics will be send are automatically generated from message fields.
`camera__rgb__image_rect` => `/camera/rgb/image_rect`
* Automatically republish messages in OCS side
=> [jsk_network_tools] Script for DRC-highspeed-link communication

jsk_network_tools/CMakeLists.txt, jsk_network_tools/launch/simple_silverhammer_openni_sample.launch, jsk_network_tools/msg/OpenNISample.msg, jsk_network_tools/scripts/silverhammer_highspeed_receiver.py, jsk_network_tools/src/jsk_network_tools/silverhammer_util.py
Add openni2 sample for highspeed streaming using silverhammer toolkit and recover message if possible of missing packets
=> [jsk_network_tools] openni sample and recover missing packets 

3rdparty/mini_maxwell/scripts/drc_2015_environment.py
=> [mini_maxwell] Fix minimaxwell configuration not to drop all the packets

jsk_topic_tools/catkin.cmake, jsk_topic_tools/include/jsk_topic_tools/snapshot_nodelet.h, jsk_topic_tools/jsk_topic_tools_nodelet.xml, jsk_topic_tools/src/snapshot_nodelet.cpp
Snapshot nodelet
* publish only one message after ~request service is called
=> [jsk_topic_tools] Add new utility to take snapshot of topic

jsk_tilt_laser/launch/multisense.launch
update multisense.launch, because this change https://github.com/jsk-ros-pkg/jsk_common/commit/39590758aa45ae9de38bf2fa05f55a81059af03d did not include tf publisher for multisense
=> update multisense launch for using with real robot

3rdparty/downward/CMakeLists.txt, 3rdparty/downward/Makefile
=> use jsk-ros-pkg/archives for download tgz

jsk_tilt_laser/launch/multisense.launch, jsk_tilt_laser/package.xml
Add laser filter to multisense scan
=> [jsk_tilt_laser] Add laser_filters to multisense

jsk_network_tools/scripts/heartbeat_master.py
Add parameter to set rate in heartbeat_master.py
=> add parameter to set rate

jsk_tilt_laser/launch/multisense.launch
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/597
=> [jsk_tilt_laser] Add ~overwrap_angle parameter to multisense.launch

jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
~region_continuous_publish parameter and if it's true, image_view2 will keep publishing region selected by user
=> [image_view2] Add ~region_continuous_publish to keep publishing selected region

jsk_tools/bin/force_to_rename_changelog_user.py
=> [jsk_tools] Add progress bar to force_to_rename_changelog_user.py

jsk_tools/package.xml, jsk_tools/src/bashrc.ros, jsk_tools/src/zshrc.ros
=> [jsk_tools] Add percol utility

jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
Selecting straight line in image_view2
=> [image_view2] Add new interaction mode to select line

jsk_network_tools/README.md, jsk_network_tools/scripts/silverhammer_highspeed_receiver.py
Add PESIMISTIC mode not to concatenate missing packets with 0.
=> [jsk_topic_tools] Add pesimistic mode for highspeed receiver

jsk_tilt_laser/launch/multisense.launch
@YoheiKakiuchi @orikuma @terasawa Be careful about this update
1) use multisense.launch, it support launch_robot_state_publisher argument
2) fix name to change speed of spindle laser
=> [jsk_tilt_laser] Update multisense.launch according to the latest update

jsk_topic_tools/README.md, jsk_topic_tools/include/jsk_topic_tools/color_utils.h, jsk_topic_tools/mainpage.dox
I don't know we should use doxygen or manually written markdown.
=> [jsk_topic_tools] Add documentation about color_utils.h

jsk_network_tools/euslisp/angle-vector-compress.l
* Compute correct modulo of infinite rotational angle
=> [jsk_network_tools] Fix compressing joint-angles of infinite joint

jsk_network_tools/euslisp/angle-vector-compress.l, jsk_network_tools/launch/joint_state_compress_sample.launch, jsk_network_tools/launch/joint_state_compress_sample.rviz
* Show difference between end effector
=> Update sample of compressing joint angle

jsk_topic_tools/scripts/bag2csv.py
add rosbag csv exporter since rqt_bag no longer supports csv export.
=> Add rosbag2csv

jsk.rosinstall
=> Removed username from jsk.rosinstall

jsk_ros_patch/image_view2/CMakeLists.txt, jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2_node.cpp
=> [image_view2] Separate main function to another cpp file

jsk.rosbuild
@furushchev please check if this is ok
=> [jsk.rosbuild] remove pip, we install python-pip

bayesian_belief_networks/setup.py
From discussion #772 
Still not solve the problem of dist-packages / site-packages.
This just solve the problem of version number.
=> [bayesian_belief_networks] Fix setup.py for installing python

jsk_tools/bin/ros_console.py, jsk_tools/package.xml
My solution for https://github.com/euslisp/EusLisp/issues/85
It's a terminal version of rqt_console. It's just a hacky code to output /rosout to your terminal.
I don't know if it's useful or not, but we don't need to afraid of dogfooding it.
=> [jsk_tools] Add script to see rosout in terminal

jsk_tools/CMakeLists.txt
=> need to copy global_bin for devel config too

3rdparty/ffha/Makefile
related to https://github.com/jsk-ros-pkg/archives/pull/2
=> use jsk-ros-pkg/archives for downloading ffha source

jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
=> [image_view2] Support poly mode to select polygonal region on image

jsk_tools/src/zshrc.ros
changed zshrc.ros just like bashrc.ros
=> rename rossetrobot -> rossetmaster, keep rossetrobot for backword compatibility

jsk_tools/package.xml
https://github.com/jsk-ros-pkg/jsk_demos/issues/311
=> [jsk_tools] Add rqt_reconfigure to run_depend

jsk.rosbuild
=> Remove oracke-java7 from jsk.rosbuild

jsk.rosbuild
For https://github.com/jsk-ros-pkg/jsk_common/pull/835#issuecomment-87674867
=> [jsk.rosbuild] add -y option to add-apt-repository

jsk_tools/CMakeLists.txt, jsk_tools/env-hooks/99.jsk_tools.zsh, jsk_tools/src/zshrc.ros
https://github.com/jsk-ros-pkg/jsk_common/pull/845
=> [jsk_tools/zshrc.ros] use env-hooks to store contents of zshrc.ros

jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
With param, this will show the grid.
=> [image_view2] add grid option

jsk_ros_patch/image_view2/CMakeLists.txt, jsk_ros_patch/image_view2/cfg/ImageView2.cfg, jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
=> [jsk_perception] add dynamic reconf for image_view2

posedetection_msgs/CMakeLists.txt, posedetection_msgs/src/feature0d_to_image.cpp
it publish sensor_msgs/Image on topic feature0d_to_image/output
=> [posedetection_msgs] Add feature0d_to_image node

jsk_ros_patch/image_view2/cfg/ImageView2.cfg, jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/image_view2.h
=> [image_view2] add Fisheye Grid Line option

jsk_network_tools/euslisp/angle-vector-compress.l, jsk_network_tools/test/launch_joint_state_compressor.xml
please do not merge until travis passed
- [jsk_network_tools/test/launch_joint_state_compressor.xml] set ROBOT environment for test (and this should be removed), see  https://github.com/jsk-ros-pkg/jsk_common/commit/39089ecfc793ac655d45552545ddc13c1fe87b09#commitcomment-10899961
=> fix to pass travis test

jsk_network_tools/euslisp/joint-state-compressor.l, jsk_network_tools/euslisp/joint-state-decompressor.l
Fix for https://github.com/jsk-ros-pkg/jsk_common/commit/39089ecfc793ac655d45552545ddc13c1fe87b09#commitcomment-10899961
=> [jsk_network_tools] Use ~robot parameter and it's initialized to ROBOT environment variable

jsk_tools/package.xml, jsk_tools/src/git_commit_alias.py
```
rosdep update
roscd && cd ..
rosdep install --from-paths . -y -r
```
=> [jsk_tools] now you can install pygithub3 by rosdep install

jsk.rosinstall.hydro
Need to re-compile it to solve https://github.com/ros-perception/pcl_conversions/pulls
=> [jsk.rosinstall.hydro] Add image_pipeline to run without pcl_conversions bug

jsk_tools/bin/check_host_sanity.py, jsk_tools/test/sample.yaml
Utility script to check `/etc/hosts` sanity for limited network robot
=> [jsk_tools] Script to check /etc/hosts sanity

jsk_data/launch/common_record.launch, jsk_data/launch/hrp2_record.launch, jsk_data/launch/multisense_play.launch
* add save_multisense parameter
* enable to select use_depth_image_proc (new default) or use_stereo_image_proc (previous default)
=> Change hrp2 rosbag record and play

jsk_tools/env-hooks/99.jsk_tools.sh
issue: https://github.com/jsk-ros-pkg/jsk_common/issues/899
=> [jsk_tools] store correctly default rosmaster by rossetdefault in bash

jsk_data/Makefile
**Usage**
```
USER=wada make large-list KEYWORD=jsk_2014_picking_challenge
```
=> [jsk_data] Add KEYWORD to large-list/small-list target in Makefile

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h, jsk_topic_tools/include/jsk_topic_tools/log_utils.h
It provides  macros like `JSK_ROS_INFO`, `JSK_NODELET_INFO`
=> [jsk_topic_tools] Add log_utils.h to print with __PRETY_FUNCTION__

jsk_data/Makefile
By this PR, you can set `ARIES_USER` to set as default username to login aries.
In my case, `USER` value is `wkentaro` but username in aries is `wada` so I can
tell the Makefile my username by adding a line in my bashrc like below::
```
export ARIES_USER="wada"
```
=> [jsk_data] env value ARIES_USER will be default username to login aries

jsk_topic_tools/test/test_topic_buffer.test
=> [jsk_topic_tools] Longer test duration for topic_buffer/hztest_chatter_update

jsk_tilt_laser/launch/multisense_laser_pipeline.launch
0.01 m resolution is necessary for footstep planning
=> [jsk_tilt_laser] More detailed laser pointcloud for precise perception

jsk_network_tools/scripts/silverhammer_lowspeed_receiver.py
https://github.com/jsk-ros-pkg/jsk_demos/issues/669#issuecomment-101901555
=> [jsk_network_tools/silverhammer_lowspeed_receiver] Force to disable timeout

jsk_network_tools/scripts/silverhammer_highspeed_receiver.py
This commit tries to fix for the issue of silverhammer communication flutter.
=> [jsk_network_tools] multiprocess silverhammer receiver

jsk_data/launch/common_record.launch
I use this topic when using drive_recogntion.sh, so I want to add this topic.
=> add  recording magnetometer

jsk_network_tools/scripts/expand_udp_receive_buffer.sh, jsk_network_tools/scripts/silverhammer_highspeed_receiver.py
Changing kernel options by `sysctl -w` command is not persistent.
I added scripts to change buffer size persistent and check logic.
=> Udp buffer size checker

jsk_network_tools/scripts/silverhammer_highspeed_receiver.py
=> [jsk_network_tools] Use loginfo instead of logwarn in silverhammre

jsk_tools/README.md, jsk_tools/src/jsk_tools/sanity_lib.py
2 Edition
- add echo option
- You can show the topic value if you want.
- The echo content is noarray.
- you don't anymore to set the topic class name
- HOWEVER, to prevent destroying interface, I keep the class arguments.
=> Add echo option for checkIsTopicPublished

jsk_tools/src/jsk_tools/sanity_lib.py
=> add check usb exist with lsusb

jsk_tools/src/jsk_tools/sanity_lib.py
Adding the ok/error custom message option
=> add sub ok/error message option to isMasterHostAlive

jsk_tools/src/jsk_tools/sanity_lib.py
https://github.com/jsk-ros-pkg/jsk_common/pull/965#issuecomment-108093040
=> add expect of usb to check

jsk_tools/src/jsk_tools/sanity_lib.py
We now can test with
```
checkUSBExist("38d6", "0002", 4, "hrp2017c", error_msg="Waaaa")
```
=>  add host option to USB Check

jsk_tools/src/jsk_tools/calc_md5.py, jsk_tools/src/jsk_tools/sanity_lib.py
Very simple script only for check param.
I couldn't find out the way to get the result from mosh, so I use now ssh.
Usage:
```
check_param baxter@localhost /robot_description
```
=> check local remote ROS Parameter diff

jsk_network_tools/test/silverhammer_lowspeed_load_test_fc.launch, jsk_network_tools/test/silverhammer_lowspeed_load_test_ocs.launch
=> [jsk_network_tools] add set send rate lowspeed request; variable send_rate test

jsk_tools/src/jsk_tools/sanity_lib.py
- use `grep -v grep`
- remove duplicated if
- remove unneeded message
=> [jsk_tools/sanity_libs.py] modify small parts of bags

jsk_data/launch/hrp2_play.launch
Fixed default ROBOT name "HRP2JSKNTS" to "$(env ROBOT)" as #997
=> Fix default ROBOT name

jsk_tilt_laser/CMakeLists.txt, jsk_tilt_laser/package.xml, jsk_tilt_laser/src/multisense_killer.cpp
see 
https://bitbucket.org/crl/multisense_ros/issue/49/multisense-broadcasts-a-lot-of-packets
=> [jsk_tilt_laser] Add multisense_killer to kill multisense streaming if host PC is down

jsk_topic_tools/include/jsk_topic_tools/relay_nodelet.h, jsk_topic_tools/include/jsk_topic_tools/vital_checker.h, jsk_topic_tools/src/relay_nodelet.cpp, jsk_topic_tools/src/vital_checker.cpp
=> [jsk_topic_tools/Relay] Add more readable diagnostic including last time it receives input topic

jsk_tools/bin/monitor_roscore.py, jsk_tools/bin/roscore_monitor.py, jsk_tools/src/jsk_tools/sanity_lib.py
=> [jsk_tools] Add monitoring script to check roscore CLOSE_WAIT num

jsk_tools/bin/bag_plotter.py, jsk_tools/package.xml, jsk_tools/src/jsk_tools/bag_plotter.py
Only for bag files, no real time plotting is supported.
Usage:
`rosrun jsk_tools bag_plotter.py hoge.bag hoge.yaml`
Yaml format is:
```
global:
layout: "vertical"
plots:
- title: "pose_x and pose_y"
type: "line"
topic: ["/Board/pose", "/Board/pose"]
field: ["pose/position/x", "pose/position/y"]
- title: "pose_x"
type: "line"
topic: ["/Board/pose"]
field: ["pose/position/x"]
- title: "pose_y"
type: "line"
topic: ["/Board/pose"]
field: ["pose/position/y"]
```
It outputs
=> [jsk_tools] Add plotting code from bag file

jsk.rosbuild
```
./jsk.rosbuild -y -s --rtm --from-source -r hrpsys,rtm-ros-robotics/rtmros_common indigo
```
download only hrpsys and rtmros_common, so they do not have to compile everything written in jsk.rosinstall
=> jsk.rosbulid: add -r option to specify package to download

jsk_tools/env-hooks/99.jsk_tools.sh
=> [jsk_tools/99.jsk_tools.sh] Safer rost and rosn func and also supports rosmsg show

jsk_topic_tools/src/standalone_complexed_nodelet.cpp
fields and read parameter from ~nodelet_%lu as well as ~nodelet
=> [jsk_topic_tools/standalone_complexed_nodelet] Support if and unless

jsk_tilt_laser/launch/multisense_laser_pipeline.launch
=> [jsk_tilt_laser] Rewrite multisense_laser_pipeline.launch with standalone_complexed_nodelet

jsk_tools/CMakeLists.txt, jsk_tools/dot-files/dot.emacs, jsk_tools/dot-files/tmux.conf
to share common setup in shared-users
=> [jsk_tools] Add dot-files directory, which is copied from JSK internal svn

jsk.rosinstall
see https://github.com/jsk-ros-pkg/jsk_common/issues/1055
=> [jsk.rosinstall] Add naoqi_bridge_msgs

jsk_data/scripts/rosbag_always.py
colorize message about removing bag files
=> [jsk_data/rosbag_always.py] Supress message about directory size and

jsk_topic_tools/README.md
BTW, I should send this feature to upstream but we need to use indigo to motivate myself.
=> [jsk_topic_tools] Add readme about standalone_complexed_nodelet

jsk.rosbuild
see https://github.com/jsk-ros-pkg/jsk_common/issues/861
=> [jsk.rosbuild] Print message when jsk.rosbuild finishes

jsk_tools/README.md, jsk_tools/bin/bag_plotter.py, jsk_tools/src/jsk_tools/bag_plotter.py
Update bag_plotter.py to visualize bag recorded by jsk_data/rosbag_always.py
It should be replaced by mongodb logging system.
This PR includes several features and commits but it is because of current travis is unstable.
=> [jsk_tools/bag_plotter] Update bag_plotter.py to visualize bag recorded by jsk_data/rosbag_always.py

jsk_data/launch/rosbag_always_run_rosbag.launch, jsk_data/scripts/rosbag_always.py
=> [jsk_tools] Use roslaunch internaly in rosbag_always.py in order to

jsk_coordination_system/dynamic_tf_publisher/src/tf_publish.py
=> [dynamic_tf_publisher] Use with to acquire lock

.travis.yml
Relates to: https://github.com/jsk-ros-pkg/jsk_common/pull/1018
=> [.travis.yml] jsk_network_tools is also tested in jade

jsk_tilt_laser/launch/multisense_laser_pipeline.launch
velocity
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/1116
=> [jsk_tilt_laser] Specify twist_frame_id of multisense laser to publish

jsk_tilt_laser/config/multisense_local_views.perspective, jsk_tilt_laser/launch/multisense_local_view.launch
@YuOhara @orikuma 
This launch file should work if you can run multisense correctly.
```
roslaunch jsk_tilt_laser multisense_local_view.launch 
```
=> [jsk_tilt_laser] Add viewer to check multisense local topics

jsk.rosbuild
add install option (rbrapp and h8_tools)
https://github.com/jsk-ros-pkg/rbrapp
https://github.com/jsk-ros-pkg/h8_tools
=> add rbrapp and h8_tools install

jsk_data/CMakeLists.txt, jsk_data/env-hooks/99.jsk_data-completion.bash, jsk_data/env-hooks/99.jsk_data-completion.zsh, jsk_data/env-hooks/99.jsk_data.bash, jsk_data/env-hooks/99.jsk_data.sh, jsk_data/env-hooks/99.jsk_data.zsh
Just with Makefile is not useful.
Please run `$ jsk_data` to see usage.
=> Add jsk_data function to handle data from anywhere

jsk.rosbuild
=> Check rosdep version in jsk.rosbuild

jsk_tools/CMakeLists.txt, jsk_tools/env-hooks/99.jsk_tools-completion.bash, jsk_tools/env-hooks/99.jsk_tools-completion.zsh
This should be a cool feature for user who restarts travis often.
=> [jsk_tools] Add completion for restart_travis

jsk.rosbuild
Add install option euslib, jsk_tendon_robot, unreleased
=> Modified jsk.rosbuild

.travis.yml
I think we do not need USE_DEB=false test any more.
=> Do not test USE_DEB=false

README.md
ppa is fixed https://github.com/raelgc/scudcloud/pull/228
=> Update document about scudcloud because the ppa is updated to solve 12.04 issue

jsk_data/src/jsk_data/cli.py, jsk_data/src/jsk_data/util.py
**Feature**
* Show id, title and download url for specified file. (title is usually same as filename)
* Show download command with `-d` or `--download-cmd` option.
=> [jsk_data] Add pubinfo subcommand

jsk_data/src/jsk_data/ssh.py
=> [jsk_data] Config key check when getting config from .ssh/config

jsk.rosinstall
face_recognitionはソースから入れてコンパイルしてやらないと
interactive_behavior_201409のコンパイルが通らないので追加しました。
=> Added face_recognition in jsk.rosinstall.

jsk_data/launch/pr2_play.launch
Update for latest pr2 camera namespace .
=> [jsk_data] add camera parm to pr2_play.launch

jsk_topic_tools/src/rosparam_utils.cpp
For: https://github.com/jsk-ros-pkg/jsk_recognition/issues/1188
=> [jsk_topic_tools] Ros error for rosparam type conversion

jsk_data/src/jsk_data/cli.py, jsk_tools/src/jsk_tools/__init__.py, jsk_tools/src/jsk_tools/cltool.py
see: https://github.com/jsk-ros-pkg/jsk_common/issues/1141#issuecomment-145332290
=> [jsk_data] Select filename interactively with percol in pubinfo

jsk_data/src/jsk_data/cli.py
=> [jsk_data] Select filename at getting with jsk_data

jsk_data/scripts/hrp2_rosbag_always.sh
https://github.com/start-jsk/rtmros_hrp2/pull/306
で必要なtopicを追加しました.
=> [jsk_data] Add new rosbag subscribe topic 

jsk_topic_tools/README.md, jsk_topic_tools/scripts/pose_stamped_publisher.py
```
$ rosrun jsk_topic_tools pose_stamped_publisher.py 0 0 0.5 0 0 0 odom 10 
```
=> [jsk_topic_tools] Utility to publish PoseStamped with given static transformation

jsk_tools/env-hooks/99.jsk_tools.sh
=> [jsk_tools] Correct order of ROS_IP in list of hostname -I

jsk_tools/src/jsk_tools/bag_plotter.py
=> [jsk_tools] show minorticks and grid

README.md
like https://github.com/swri-robotics/mapviz/blob/indigo-devel/README.md#build-status
=> Show deb build status in table

jsk_tilt_laser/launch/multisense.launch
This PR is assumed not to effect nothing to previous pipeline.
I only intended to separate existing stereo pipeline.
Please merge after https://github.com/jsk-ros-pkg/jsk_recognition/pull/1268
=> [jsk_tilt_laser] Add separated pipeline for stere image

jsk_topic_tools/src/jsk_topic_tools/transport.py
=> [jsk_topic_tools] Describe about ~always_subscribe in warning

jsk_data/launch/urata_record.launch
urataロボット系のrosbag recordのlaunchを加えました．
=> [jsk_data/launch] add urata_record.launch

jsk_ros_patch/image_view2/image_view2.cpp
=> [image_view2] Visualize depth image

jsk_tools/CMakeLists.txt, jsk_tools/bin/run_tmux
That is described here:
http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB
Sample: https://gist.github.com/wkentaro/84e4cd9ee84a206cef3e
=> [jsk_tools] Install run_tmux for gdb debugging

jsk_tools/env-hooks/99.jsk_tools.sh
=> [jsk_tools] Add rosrecord shell function

jsk_topic_tools/package.xml
Closes https://github.com/jsk-ros-pkg/jsk_common/issues/1230
=> build_depend -> test_depend roscpp_tutorials

jsk_tools/README.md
for jsk-ros-pkg/jsk_docs, this closes #1251
=> [jsk_tools] Fix style of markdown

jsk_tools/bin/ws_doctor.py
wstool>=0.1.12 does show equivalent information by ``wstool info``
=> [jsk_tools] Remove ws_doctor.py

jsk_topic_tools/CMakeLists.txt, jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h, jsk_topic_tools/package.xml, jsk_topic_tools/src/connection_based_nodelet.cpp
=> [jsk_topic_tools/ConnectionBasedNodelet] Support image_transport. Add advertiseImage and advertiseCamera.

jsk_topic_tools/include/jsk_topic_tools/log_utils.h
Define warnNoRemap in include guard section.
=> [jsk_topic_tools/log_utils] Fix include guard.

jsk_data/package.xml
Taking over https://github.com/jsk-ros-pkg/jsk_common/pull/1196
=> [jsk_data] Depends on jsk_topic_tools

jsk_ros_patch/image_view2/image_view2.cpp
for https://github.com/jsk-ros-pkg/jsk_common/issues/1247
=> [image_view2] avoid SEGV caused by negative width for rectangle

jsk_tools/bin/report_issue.sh
It will generate a gist like https://gist.github.com/anonymous/6e1a34227eeb8ef3013c
See #1187.
=> [jsk_tools] Add tool to help reporting issue

jsk_tools/env-hooks/99.jsk_tools.sh
Closes #1202
This is proposed by @k-okada and discussed on #1202
Modified:
jsk_tools/env-hooks/99.jsk_tools.sh
=> [jsk_tools] Add tool to make commit message informative

jsk_topic_tools/package.xml, jsk_topic_tools/src/jsk_topic_tools/transport.py
=> [jsk_topic_tools] Stop using enum34 and use just int

jsk_network_tools/package.xml, jsk_ros_patch/image_view2/test/rectangle_mouse_event.launch, jsk_tools/launch/local_pc_monitor.launch, jsk_topic_tools/package.xml
It includes #1303, #1305, #1306
=> Update travis for pip

jsk_tools/bin/git-jsk-commit
Modified:
- jsk_tools/bin/git-jsk-commit
=> [jsk_tools] Add bullet for git-jsk-commit to beautify as markdown

jsk_tools/src/topic_delay_monitor.py
upstream PR: ros/ros_comm#719
Added:
jsk_tools/src/topic_delay_monitor.py
=> [jsk_tools] Add topic delay monitor

jsk_tilt_laser/launch/multisense.launch, jsk_tilt_laser/launch/multisense_laser_pipeline.launch
1. Add /multisense_local/joint_states topic for the nodes which
are only interested in multisense joint angles
2. Remap /tf to /tf_null in multisense_laser to avoid tf listening
from pcl/PassThrough
=> [jsk_tilt_laser] Optimize /joint_states and /tf around multisense.

jsk_data/launch/kinect2_bridge_play.launch, jsk_data/package.xml
The reason I'd like to put this at this package is
that installing kinect2_bridge package is not so easy.
=> [jsk_data] Add playback launch for kinect2 using kinect2_bridge

jsk_tools/env-hooks/99.jsk_tools.bash, jsk_tools/env-hooks/99.jsk_tools.zsh
Upstream PR: https://github.com/ros/ros/pull/99
Modified:
- jsk_tools/env-hooks/99.jsk_tools.bash
- jsk_tools/env-hooks/99.jsk_tools.zsh
=> [jsk_tools] Add rosview

jsk_tools/src/test_topic_published.py
Modified:
- jsk_tools/src/test_topic_published.py
=> [jsk_tools] Reasonable test result message

jsk_data/README.md, jsk_data/src/jsk_data/cli.py, jsk_data/src/jsk_data/gdrive.py
Modified:
- jsk_data/src/jsk_data/cli.py
- jsk_data/src/jsk_data/gdrive.py
=> [jsk_data] Add pubopen subcommand to open GoogleDrive

doc/index.rst, doc/tips.md
Modified:
- doc/index.rst
Added:
- doc/tips.md
=> Add tips to use ccache

jsk_tools/bin/battery_capacity_summary.py
=> [jsk_tools/bin/battery_capacity_summary.py] more battery info

jsk_tilt_laser/launch/multisense_laser_pipeline.launch
=> [jsk_tilt_laser] Remap tf topics only for pcl_ros nodelets

CONTRIBUTION.md
Modified:
- CONTRIBUTION.md
```
Running Sphinx v1.3.3
making output directory...
Cloning into 'jskeus'...
HEAD is now at 22a3572 Build documents from d53c484e6bbc6cb052da1b3f89e2a6445af9621e
Cloning into 'jsk_common'...
HEAD is now at 27e1d1b Merge pull request #1330 from garaemon/remap-tf-for-pcl-nodelets
Cloning into 'jsk_roseus'...
HEAD is now at dc27db9 Merge pull request #423 from garaemon/deb-build-table
Cloning into 'jsk_recognition'...
HEAD is now at e1c9976 Merge pull request #1470 from wkentaro/label-to-cpi
Cloning into 'jsk_visualization'...
HEAD is now at 99a9b3e Merge pull request #560 from garaemon/plot-2d-to-support-new-msg
Cloning into 'jsk_planning'...
HEAD is now at 6c9c9ef Merge pull request #38 from Grollo/patch-1
Cloning into 'jsk_control'...
HEAD is now at b82c14e …
```
=> Fix typo in code block in CONTRIBUTION.md

jsk_tools/src/jsk_tools/bag_plotter.py
Modified:
- jsk_tools/src/jsk_tools/bag_plotter.py
=> [jsk_tools/bag_plotter] Support messages which does not have header

jsk_tools/src/jsk_tools/bag_plotter.py
=> [jsk_tools] Add label field to customize legend

jsk_topic_tools/scripts/bag2csv.py
--flattenオプションを加えると，中身が配列の場合に各要素をカンマ区切りで出力します．
デフォルトの挙動は変わらないです．
@kozuki さんのbagファイルで確認しました．
=> [jsk_topic_tools/scripts/bag2csv.py] support flatten option in bag2csv.

jsk_tools/src/jsk_tools/bag_plotter.py
```
- title: "lleg current"
topic: [/motor_states/motor_current]
field: ["data[6,8:10]"]
```
=> bag_plotterのyamlファイルでプロットするfieldを個別に選択できるように

jsk_data/launch/kinect2_bridge_play.launch
Depends on https://github.com/ros-perception/image_pipeline/commit/8d076d33a9ab48f92d0d30cd61913d69ab9d3bfe
So need to wait for next release.
Modified:
- jsk_data/launch/kinect2_bridge_play.launch
=> [jsk_data] exact_sync: true for publishing points

jsk_tools/bin/git-jsk-commit
Closes https://github.com/jsk-ros-pkg/jsk_common/issues/1319
Modified:
- jsk_tools/bin/git-jsk-commit
=> [jsk_tools] Use "$@" to pass arguments in git-jsk-commit

jsk_topic_tools/src/jsk_topic_tools/transport.py
Modified:
- jsk_topic_tools/src/jsk_topic_tools/transport.py
=> [jsk_topic_tools] Set property is_initialized

jsk_coordination_system/dynamic_tf_publisher/cfg/TfParameter.cfg, jsk_network_tools/cfg/SilverhammerHighspeedStreamer.cfg, jsk_ros_patch/image_view2/cfg/ImageView2.cfg, jsk_ros_patch/multi_map_server/CMakeLists.txt, jsk_tilt_laser/CMakeLists.txt
- remove dynamic_reconfigure.parameter_generator for rosbuild
- Add include_dirs for multi_map_server
- CATKIN_INCLUDE_DIRS -> catkin_INCLUDE_DIRS
=> another trial for 1353

jsk_ros_patch/image_view2/image_view2.cpp
Modified:
- jsk_ros_patch/image_view2/image_view2.cpp
=> [image_view2] Fix header of screenrectangle topic to include frame_id

jsk_tilt_laser/cfg/DynamixelTiltController.cfg
this will fix https://github.com/jsk-ros-pkg/jsk_common/issues/1359
Close #1359
=> remove dynamic_reconfigure.parameter_generator, which only used for rosbuild

doc/jsk_tools/cltools/rosview.rst, jsk_tools/env-hooks/99.jsk_tools.bash, jsk_tools/env-hooks/99.jsk_tools.zsh
Modified:
- jsk_tools/env-hooks/99.jsk_tools.bash
- jsk_tools/env-hooks/99.jsk_tools.zsh
=> [jsk_tools] Reuse roscat in rosview shell function

.travis.rosinstall, .travis.yml
because release on deb has been stopped.
=> Build packages from source for hydro on travis

jsk_topic_tools/src/connection_based_nodelet.cpp
Modified:
- jsk_topic_tools/src/connection_based_nodelet.cpp
=> [jsk_topic_tools] Set flag of subscribed even when always_subscribe

jsk_tools/CMakeLists.txt, jsk_tools/cmake/run_shell_test.py, jsk_tools/cmake/shell_test.cmake.em
Modified:
- jsk_tools/CMakeLists.txt
Added:
- jsk_tools/cmake/run_shell_test.py
- jsk_tools/cmake/shell_test.cmake.em
=> [jsk_tools] Test tool with shell command with catkin

jsk_ros_patch/image_view2/image_view2.cpp
=> fix for error when using opencv3

jsk.rosinstall
=> [jsk_common] remove jsk-ros-pkg/openrave_planning from jsk.rosintall

jsk_tools/launch/record_axis_camera.launch
https://github.com/ros-perception/image_pipeline/issues/187
=> Fix video recording to avoid the bug in image_view

jsk_data/CMakeLists.txt, jsk_data/cfg/DataCollectionServer.cfg, jsk_data/node_scripts/data_collection_server.py, jsk_data/package.xml, jsk_data/sample/config/sample_data_collection_server.perspective, jsk_data/sample/sample_data_collection_server.launch
- Add sample for data_collection_server in jsk_data
- Return saved message as TriggerResponse in data_collection_server
- Make params as optional for data_collection_server
- Change dynamically save_dir parameter in data_collection_server
=> Enhance data_collection_server regarding of response, params, and sample

jsk_data/node_scripts/data_collection_server.py, jsk_data/package.xml
```
% rosdep resolve python-yaml --os=ubuntu:trusty
#apt
python-yaml
% rosdep resolve python-yaml --os=ubuntu:saucy 
#apt
python-yaml
```
=> [jsk_data] Add YAML savetype to data_collection_server

jsk_data/node_scripts/camera_coords_change_trigger.py
Originally developped in
https://github.com/furushchev/jsk_semantics_201607/blob/master/jsk_pr2_wandering/node_scripts/camera_coords_change_trigger.py.
=> [jsk_data] Add trigger node for data collection by camera coords change

jsk_data/src/jsk_data/download_data.py
=> [jsk_data] Support setting abspath for downloading data

jsk_data/CMakeLists.txt, jsk_data/launch/baxter_record.launch, jsk_data/launch/common_record.launch, jsk_data/launch/hrp2_record.launch, jsk_data/launch/pr2_record.launch, jsk_data/launch/template_pr2_record.launch, jsk_data/launch/urata_record.launch, jsk_data/package.xml
rebased version of #1438
- [jsk_data] add machine argument for record.launch
- [jsk_data] add bagfile_prefix arg for record.launch
=> [jsk_data] add machine argument for record.launch

jsk_data/src/jsk_data/download_data.py
- For multiple workspaces like in jenkins.
=> [jsk_data] Create softlink for extracted files in download_data

jsk_tools/package.xml, jsk_tools/src/post_to_slack_server
Depends on https://github.com/jsk-ros-pkg/jsk_common_msgs/pull/13
=> [jsk_tools] Post to slack via String message input

jsk_data/node_scripts/data_collection_server.py
- support no-header message
- add YAML topic savetype
=> [jsk_data] add YAML topic savetype

jsk_data/node_scripts/data_collection_server.py
- fix typo
- fix indent
- fix visual indent
- fix line length max
=> [jsk_data/data_collection_server] fix typo in data_collection_server

doc/jsk_topic_tools/scripts/tf_to_transform.rst, jsk_topic_tools/scripts/tf_to_transform.py
Usage:
```
$ rosrun jsk_topic_tools tf_to_transform.py -h
usage: tf_to_transform.py [-h] [--duration DURATION]
[parent_frame_id] [child_frame_id]
positional arguments:
parent_frame_id       parent frame id
child_frame_id        child frame id
optional arguments:
-h, --help            show this help message and exit
--duration DURATION, -d DURATION
Duration [s]: default=1.0
```
param:
`duration` : duration
`parent_frame_id`: parent frame id
`child_frame_id`: child frame id
Output:
`TransformStamped`
=> [jsk_topic_tools] add tf_to_transform node

jsk_data/node_scripts/data_collection_server.py
MERGE AFTER #1477
- set `slop` as rosparam
- show warning about slop and time
=> [jsk_data/data_collection_server.py] set slop as rosparam

jsk_data/src/jsk_data/gdrive.py
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1484
@rkoyama1623 これでいいでしょうか？
=> [jsk_data] Check if gdrive authorization has been successfully completed

jsk_data/CMakeLists.txt
=> Strict rule of installing scripts

jsk_data/src/jsk_data/cli.py, jsk_data/src/jsk_data/download_data.py
Why
---
I found forcely chaning filename is a bit too strict.. ;)
=> [jsk_data] Make stamping as optional in jsk_data

jsk_tools/env-hooks/99.jsk_tools.sh
=> Set WITHOUT_ROS_PROMPT at _update_prompt to fix #1494

.travis.yml, jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/test/publish_lena.py
see https://github.com/ros-perception/image_pipeline/pull/184 for more info
=> add cv::waitKey for opencv3

jsk_data/src/jsk_data/download_data.py
As I suggested at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1988#issuecomment-267019667
=> Check if specified md5 has 32 charactors

jsk_data/package.xml
Be proposed at https://github.com/jsk-ros-pkg/jsk_common/pull/1493#issuecomment-269746137
=> Add my name to package.xml as a maintainer

jsk_tools/src/generate_deb_status_table.py
For https://github.com/jsk-ros-pkg/jsk_common/pull/1491#issuecomment-270557750
=> Cope with arm64 for deb status table

jsk_tools/package.xml, jsk_tools/src/generate_deb_status_table.py
https://github.com/jsk-ros-pkg/jsk_common/pull/1490#issuecomment-263434307
=> Add python-tabulate-pip as a dependency

jsk_tools/src/test_topic_published.py
Not needed by https://github.com/jsk-ros-pkg/jsk_recognition/pull/2008, but this is awared to be necessary by that.
Sent PR: https://github.com/ros/ros_comm/pull/973
=> [jsk_tools] Improve test_topic_published.py (check /use_sim_time neatly)

jsk_tools/src/jsk_tools/migration.py
For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1917#issuecomment-283231789
=> Fix migration of from XXX.[srv|msg] import YYY

jsk_data/node_scripts/data_collection_server.py
For small size data using npz_compressed.
=> [jsk_data] Dump numpy.ndarray as npz file in data_collection_server.py

jsk_data/node_scripts/data_collection_server.py
-	modified:   node_scripts/data_collection_server.py
=> Add saving mode without resquest to data_collection_server

doc/jsk_topic_tools/class/connection_based_nodelet.md, doc/jsk_topic_tools/class/diagnostic_nodelet.md, doc/jsk_topic_tools/class/python_connection_based_transport.md
=> Improve docs for ConnectionBased class for both C++ and Python

jsk_data/launch/pr2_play.launch, jsk_data/launch/pr2_play.sh
e.g.
```bash
rosrun jsk_data pr2_play.sh data.bag -l --pause
```
=> [jsk_data][pr2_play.sh] support other rosbag arguments

jsk_data/src/jsk_data/download_data.py
This PR enables to optionally share the directory for cached downloaded data among users by setting environment variable `JSK_DATA_CACHE_DIR`.
This will close #1529.
- support custom cache directory for downloading data
1. use environment variable `JSK_DATA_CACHE_DIR` if defined 
2. use `ROS_HOME/data` if `ROS_HOME` is defined
3. use `~/.ros/data`
- chmod cache dir to allow writing by other users on a computer
=> [jsk_data][download_data] support custom download dir / chmod

doc/jsk_topic_tools/lib/standalone_complexed_nodelet.rst
I'm a newbie of this feature, and if it is not right, please let me know. I'll close it.
(Actually, I'm not sure what ```dynamic loading/unloading of nodelet classes``` is...)
=> [doc/lib] modify standalone_complexed_nodelet doc

jsk_data/src/jsk_data/download_data.py
**Before**
```
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/drill.pcd'...
...done
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/2016-10-26-02-09-51_coffee_cup.pcd'...
...done
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/room73b2_table.bag'...
...done
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/sample_add_color_from_image_20170319.bag'...
...done
Decompressing '/home/wkentaro/Projects/jsk_apc/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros/sample/data/sample_add_color_from_image_20170319.bag'...
...done
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/stereo_arc2017_objects.bag'...
...done
Checking md5sum of '/home/wkentaro/.ros/data/jsk_pcl_ros/2016-07-06-12-16-43-person-in-point-cloud.tgz'...
...done
Extracting …
```
=> Improve print information while download_data

.travis.yml
we can not find python module install by apt c.f. jsk-ros-pkg/jsk_3rdparty#117
=> need to use system python, with travis-python

jsk_data/node_scripts/data_collection_server.py
same as #1542
- Sleep less time in data_collection_server.py
- Return false response in data_collection_server
=> Fix data_collection_server

.travis.yml
This enables us to remove cron job from jenkins.
=> [WIP] Trigger the build of jsk-docs.rtd.org by travis

jsk_ros_patch/image_view2/test/publish_mouse_event.py
Just cleaned up unnecessary codes.
Fixes error on https://github.com/jsk-ros-pkg/jsk_recognition/pull/2207#issuecomment-339884447
=> image_view2: fix publish_mouse_event

jsk_topic_tools/include/jsk_topic_tools/stealth_relay.h, jsk_topic_tools/src/stealth_relay_nodelet.cpp
=> jsk_topic_tools: stealth_relay_nodelet: support MessageEvent

doc/jsk_data/node_scripts/data_collection_server.rst, jsk_data/node_scripts/data_collection_server.py, jsk_data/sample/sample_data_collection_server.launch
- add `timer` method for data collection
- `start_request` service to start save timer
- `end_request` service to end save timer
- add `method` param to select `request`, `message_filters` and `timer`
- add deprecated warning for `with_request`
=> add timer save request in data_collection_server

README.md
I added how to see all channels in Slack.
I sent this pull request because it took about half an hour for me to find `#travis` channels...
However, I know not all people have trouble in finding it. In that case, I will close this.
=> [README.md] add explanation how to search for channels in Slack

jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h, jsk_topic_tools/package.xml, jsk_topic_tools/src/connection_based_nodelet.cpp
Waiting for upstream:
- https://github.com/ros/nodelet_core/pull/61
=> Add warnNoRemap to ConnectionBasedNodelet

jsk_data/src/jsk_data/download_data.py, jsk_data/src/jsk_data/tests/test_download.py
Related to #1574 
In download_data.py, Add re-download phase.
=> [jsk_data] Add re-download code. Fix #1574

jsk_data/tests/test_data_collection_server.py
I missed this in https://github.com/jsk-ros-pkg/jsk_common/pull/1599#issuecomment-418374578.
=> Enable method: all in test_data_collection_server.py

jsk_tools/src/jsk_tools/bag_plotter.py
This PR add some option for bag_plotter.py
- "color" option to specify the line color of each field
- "label_font_size" and "title_font_size" global options to specify the font size of all subplot
=> Add style options

jsk_tools/src/jsk_tools/bag_plotter.py
Sorry, my #1601 had an easy bug.
=> Correct a line mistaken, easy but critical

jsk_topic_tools/cmake/nodelet.cmake
This is one possible solution for #1617
=> jsk_nodelet: fix overwritting find_package(boost)

jsk_tools/bin/battery_capacity_summary.py
Fix a column order of battery info
=> battery_capacity_summary.py: fix order of columns

jsk_data/launch/pr2_play.launch
upgrade pr2_play.launch for supporting indigo version
=> pr2_play.launch: support indigo

jsk_tools/bin/roscore_regardless.py, jsk_topic_tools/src/jsk_topic_tools/master_util.py
* Add --timeout option to change timeout duration of ping command
towards rosmaster computer.
* --timeout option defaults to 100 milli seconds.
=> [jsk_tools] Add --timeout option to roscore_regardless.py

jsk_tools/bin/battery_capacity_summary.py
`battery_capacity_summary.py` will show current voltage by this PR.
I tested with real PR2.
```
$ rosrun jsk_tools battery_capacity_summary.py
aggregating battery info...
Battery Name|         Serial|ManufactureDate|   FullCapacity|RemainingCapacity|     CycleCount|         Status
/Power System/Smart Battery 0.0|          24839|     11/27/2017|           6788|           6680|             22|            224
/Power System/Smart Battery 0.1|          24852|     11/27/2017|           6782|           6676|             22|            224
/Power System/Smart Battery 0.2|          24847|     11/27/2017|           6854|           6749|             22|            224
/Power System/Smart Battery 0.3|          24817|     11/27/2017|           6856|           6753|             21|            224 …
```
=> [jsk_tools] Show voltage in battery_capacity_summary.py

jsk_topic_tools/scripts/tf_to_pose.py
* Assign listener varaible before run timer and the callback in order
not to lookup listener variable before it is assigned.
=> Create tf.TransformListener before run timer

jsk_topic_tools/scripts/rosping_existence.py
set volume for kinetic
see https://github.com/jsk-ros-pkg/jsk_control/pull/724#issuecomment-513127598 for discussion
=> add SoundRequest.volume for kinetic

jsk_tools/bin/roscore_regardless.py
just a minor fix for roscore_regardless.py
=> fix failure on finally clause

.travis.rosinstall, .travis.rosinstall.lunar, .travis.yml
=> fix lunar build in travis

virtual_force_publisher/src/virtual_force_publisher.cpp
this PR changes `ROS_INFO` to `ROS_DEBUG` in `virtual_force_publisher`.
without this PR, log output is like below:
```
[ INFO] [1610173540.184173438] [/right_endeffector/virtual_force_publisher:ros.virtual_force_publisher]:  -0.30
66   0.2159   0.0000   0.0000   0.0000   1.0000 
[ INFO] [1610173540.184192397] [/left_endeffector/virtual_force_publisher:ros.virtual_force_publisher]:   0.143
7   0.0296  -0.4784   0.8881   0.3575   0.2890 
[ INFO] [1610173540.184211600] [/right_endeffector/virtual_force_publisher:ros.virtual_force_publisher]:  -0.31
19   0.0246  -0.0912   0.0785   0.9969   0.0000 
[ INFO] [1610173540.184232331] [/left_endeffector/virtual_force_publisher:ros.virtual_force_publisher]:   0.016
2   0.0057  -0.0039   0.3500  -0.9334   0.0794 
[ INFO] [1610173540.184268013] …
```
=> [virtual_force_publisher] use ROS_DEBUG to suppress log output

.travis.yml
=> update jsk_travis to 0.5.21

audio_video_recorder/CMakeLists.txt, audio_video_recorder/README.md, audio_video_recorder/include/audio_video_recorder/audio_video_recorder.h, audio_video_recorder/launch/audio_video_recorder.launch, audio_video_recorder/package.xml, audio_video_recorder/sample/pr2_audio_video_recorder.launch, audio_video_recorder/sample/sample_audio_video_recorder.launch, audio_video_recorder/src/audio_video_recorder.cpp, jsk_common/package.xml
=> [WIP] PR1040 Branch

doc/jsk_data/scripts/jsk_data_cli.md
Update public drive url.
See https://github.com/jsk-ros-pkg/jsk_recognition/issues/2630.
=> [jsk_data] update public drive url

jsk_data/tests/test_data_collection_server.py
The current data collectionn server test waits for data to be saved by waiting for sleep.
In Travis, sometimes the following error occurs.
```
2022-05-17T16:47:05.2086940Z ##[group]catkin_test_results
2022-05-17T16:47:05.2087101Z + error
2022-05-17T16:47:05.2087176Z + travis_time_end 31
2022-05-17T16:47:05.2087251Z + set +x
2022-05-17T16:47:05.2087549Z Full test results for 'jsk_data/test_results/jsk_data/rosunit-test_data_collection_server.xml'
2022-05-17T16:47:05.2087747Z -------------------------------------------------
2022-05-17T16:47:05.2087917Z <?xml version="1.0" encoding="utf-8"?>
2022-05-17T16:47:05.2088273Z <testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="3" time="10.604"><testcase classname="__main__.TestDataCollectionServer" name="test_all" …
```
=> Fixed data collection server test error

doc/jsk_tools/test_nodes/test_topic_published.rst, doc/jsk_topic_tools/scripts/boolean_node.rst, jsk_tools/src/test_topic_published.py, jsk_tools/test/test_topic_published.launch, jsk_topic_tools/sample/sample_boolean_node.launch, jsk_topic_tools/scripts/boolean_node.py, jsk_topic_tools/src/jsk_topic_tools/eval_utils.py, jsk_topic_tools/test/test_boolean_node.test
Now the boolean node and test_topic_published.py can set the python expression.
You may want to import libraries like the transform tool.
http://wiki.ros.org/topic_tools/transform
This PR enables that by adding `~import` param.
=> [test_topic_published.py, boolean_node.py] Enable importing modules

.github/workflows/config.yml, jsk_network_tools/setup.py, jsk_ros_patch/image_view2/CMakeLists.txt, jsk_ros_patch/image_view2/image_view2.cpp, jsk_ros_patch/image_view2/points_rectangle_extractor.cpp, jsk_tilt_laser/src/spin_laser_snapshotter.cpp, jsk_topic_tools/CMakeLists.txt, jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h, jsk_topic_tools/include/jsk_topic_tools/constant_rate_throttle_nodelet.h, jsk_topic_tools/src/block_nodelet.cpp, jsk_topic_tools/src/constant_rate_throttle_nodelet.cpp, jsk_topic_tools/src/deprecated_relay_nodelet.cpp, jsk_topic_tools/src/diagnostic_nodelet.cpp, jsk_topic_tools/src/hz_measure_nodelet.cpp, jsk_topic_tools/src/lightweight_throttle_nodelet.cpp, jsk_topic_tools/src/mux_nodelet.cpp, jsk_topic_tools/src/passthrough_nodelet.cpp, jsk_topic_tools/src/relay_nodelet.cpp, jsk_topic_tools/src/snapshot_nodelet.cpp, jsk_topic_tools/src/stealth_relay_nodelet.cpp, jsk_topic_tools/src/string_relay_nodelet.cpp, jsk_topic_tools/src/synchronized_throttle_nodelet.cpp, jsk_topic_tools/src/tests/test_log_utils_nodelet.cpp, jsk_topic_tools/src/timered_diagnostic_updater.cpp, jsk_topic_tools/src/topic_buffer_client.cpp, jsk_topic_tools/src/topic_buffer_server.cpp, jsk_topic_tools/src/vital_checker_nodelet.cpp
backcompaible version of [[ROS-O] do not specify c++ standard](https://github.com/jsk-ros-pkg/jsk_common/pull/1770) (#1770)
Closes #1770
=> add test to compile on 22.04, see #1770

jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_video.py
fetch internal version of # #1767
=> [develop/fetch] catch StopIteration when all images do not have stamp

.github/workflows/config.yml, jsk_tilt_laser/src/spin_laser_snapshotter.cpp, jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h, jsk_topic_tools/src/constant_rate_throttle_nodelet.cpp, jsk_topic_tools/src/diagnostic_nodelet.cpp, jsk_topic_tools/src/hz_measure_nodelet.cpp, jsk_topic_tools/src/lightweight_throttle_nodelet.cpp, jsk_topic_tools/src/mux_nodelet.cpp, jsk_topic_tools/src/relay_nodelet.cpp, jsk_topic_tools/src/stealth_relay_nodelet.cpp, jsk_topic_tools/src/synchronized_throttle_nodelet.cpp, jsk_topic_tools/src/timered_diagnostic_updater.cpp, jsk_topic_tools/src/topic_buffer_client.cpp, jsk_topic_tools/src/topic_buffer_server.cpp
=> add test to check c++14/C++11/C++0x

jsk_coordination_system/dynamic_tf_publisher/CMakeLists.txt, jsk_coordination_system/dynamic_tf_publisher/package.xml, jsk_coordination_system/dynamic_tf_publisher/src/tf_publish.py, jsk_coordination_system/dynamic_tf_publisher/test/tf_set.test
add test and fixes to close #1788
=> add test to check if dynamic_tf_publisher/sample/sample.launch works

jsk_data/package.xml
jsk_data/src/download_data.py requries wget
=> [jsk_data] add 'wget' to package.xml

jsk_data/src/jsk_data/download_data.py
Add `xz` support for `download_data` method of python lib.
=> [jsk_data] add xz support for download_data

.github/workflows/config.yml, jsk_rosbag_tools/CMakeLists.txt
see https://github.com/v4hn/ros-o-builder/blob/jammy-one/README.md#install-instructions for how to setup
=> .github/forkflows/config.yml: add ROS-O test

audio_video_recorder/CMakeLists.txt
It has a build_depend on message filters but was neglecting to find_package it in the CMakeLists.txt
=> [audio_video_recorder] needs to find_package message_filters

.github/workflows/config.yml, jsk_data/package.xml, jsk_ros_patch/multi_map_server/package.xml, jsk_rosbag_tools/CMakeLists.txt, jsk_rosbag_tools/package.xml, jsk_tools/package.xml
rewrited version of  #1814
use matrix.ROS_ONE_VARIANT {v4hn|tachfak} to swich the code.
=> enable noble techfak ros-o test #1814
